### ISSUE TITLE
Away mode

### ISSUE THREAD

**Issue by adrianmihalko** [nervetattoo/simple-thermostat#10]
Thanks for this great thermostat panel, this should be the default in HA Lovelace UI. I just miss the away mode feature like in was the old UI:

<img width="413" alt="screenshot 2018-12-05 at 21 44 31" src="https://user-images.githubusercontent.com/733361/49543003-530fc680-f8d7-11e8-8f64-c10a695083b2.png">

**Comment by jchasey** [comment]
Agree that showing the away mode on the card would be ideal.

**Comment by jsblake** [comment]
For what it's worth, you could always do a separate button/entity card. Since Away mode is technically applied to your whole Nest account and not just the thermostat, it somewhat makes sense to break it out from the thermostat card anyway

**Comment by nervetattoo** [comment]
I always thought of away mode as something that should absolutely not be viewed from the perspective of single entities. Either you are away or you aren't. I'll leave it open to potentially gather more input

**Comment by jsblake** [comment]
I would agree in general, but this is referring specifically to "away mode" for Nest specifically, not any concept of an "away mode" that someone might configure or create via scripts/automations/etc within their Home Assistant environment.

However, as I noted earlier, the Nest "away mode" applies to the entire Nest account, and applies to any Nest devices (cameras, security system, doorbell, locks, smoke detector, thermostat) on your Nest account. Though, there are LOTS of people who only have a thermostat on their Nest account.

**Comment by jchasey** [comment]
While setting the away mode should arguably be done 'centrally' it would be useful for there to be a visual indicator on the termostat that it is indeed in away mode, as opposed to a switch to adjust. So simply showing 'Away' on the card when the thermostat is in that state and not showing anything when not would suffice.

**Comment by mrdje** [comment]
I'm personnaly using "away mode" a lot instead of changing the targeted temperature.
For example, at night my "night mode" switch the thermostat to "away_mode" instead of changing the asked temperature.
It's sad to have an "operation mode" but having only "off" and "on" as a drop down list.

**Comment by nervetattoo** [comment]
There seems to be enough usage of away mode that I should add support for it. I'll look into the next time I spend some time on this.

**Comment by nervetattoo** [comment]
Released in [0.16.0](https://github.com/nervetattoo/simple-thermostat/releases/tag/0.16.0)
