### ISSUE TITLE
Feature request: heating state colour

### ISSUE THREAD

**Issue by craigueh** [nervetattoo/simple-thermostat#100]
Would it be possible to have the large target temp numbers change color to orange or red when the heating is running so it's clear that the heating is actually on? Currently the numbers change to red when clicked for a few seconds but if they could stay red until the target temp has been reached that would be great.
For now I just use the State: Heating to check this but it's much smaller and not as easy to see as just a color state change on the large temp number to know when my boiler is running.

Thanks

**Comment by nervetattoo** [comment]
I will not add this to the card itself, but I've added the current HVAC action as a classname on the `<ha-card>` element, which should enable to hack this yourself using [card-mod](https://github.com/thomasloven/lovelace-card-mod) doing something like:

```yaml
style: |
  ha-card.heating .current--value {
    color: red;
  }
```

**Comment by MaxVRAM** [comment]
Just to add to this for anyone after something similar

I used the following styles to colour the heat button background with the primary theme colour, but **only when the heater is active** (and not idle):

```yaml
style: |
  ha-card.heating .mode-item.active {
    background-color: var(--primary-color);
  }
  ha-card.idle .mode-item.active {
    background-color: var(--disabled-color);
  }
```

**Comment by ChristophPech** [comment]
This works fine for my regular heaters but my A/C returns it states as "Heat" and "Cool" instead of "Heating (...)" and "Cooling"
