### ISSUE TITLE
update through HACS fails

### ISSUE THREAD

**Issue by phixion** [nervetattoo/simple-thermostat#102]
Installed: 0.34.0

Updating through HACS throws an error as seen here https://i.phx.ms/5Lbh.png. Tried uninstalling, reinstalling, restarting. Other components updated fine however

**Comment by Larx** [comment]
Can confirm this.

**Comment by nervetattoo** [comment]
That's an issue with HACS not the card. I'm guessing its a variant of [this issue](https://github.com/hacs/integration/issues/922). I'm closing this and you can read up and provide more data there to have it resolved.
