### ISSUE TITLE
Compact mode does not work

### ISSUE THREAD

**Issue by deluxestyle** [nervetattoo/simple-thermostat#104]
I tried to use the compact mode but it does not work
Version: 0.34.1
Hass.io: 0.105.2

code sample:
> type: custom:simple-thermostat
          entity: climate.living_room
          step_size: 0.5
          step_layout: row
          name: false
          sensors:
            - entity: sensor.valve_living_room
              name: Ventil
          label:
            temperature: Temperatur
          control :
            _icons: true
            _names: true

**Comment by TheStigh** [comment]
> 
> 
> I tried to use the compact mode but it does not work
> Version: 0.34.1
> Hass.io: 0.105.2
> 
> code sample:
> 
> > type: custom:simple-thermostat
> > entity: climate.living_room
> > step_size: 0.5
> > step_layout: row
> > name: false
> > sensors:
> > - entity: sensor.valve_living_room
> > name: Ventil
> > label:
> > temperature: Temperatur
> > control :
> > _icons: true
> > _names: true

To get the Compact Mode, you must set **_icons** & **_names** to **false**. That is what makes it compact. Ultimately you can use --st-spacing to even shrink it more.

Play with those values, you will see it works :)

**Comment by deluxestyle** [comment]
hm, I don't get it working.
how to get the +- instead of the arrows?

**Comment by deluxestyle** [comment]
forget my last coment. It seems a chache problem. 
on my mobile it is working. on my chrome not, even after clearing the cache
