### ISSUE TITLE
More Style Examples

### ISSUE THREAD

**Issue by DrJohnT** [nervetattoo/simple-thermostat#106]
Love this card!  Much easier to use on a mobile phone than the standard thermostat card.

I was attempting to apply some CSS styling, but could not figure out the syntax.  If I use the "ha-card" example at the bottom of the readme file, then no change was made to the control.  

As to the "example-theme:" example, I have no idea where to add that YAML.  Could you please provide examples and screenshots??

**Comment by nervetattoo** [comment]
You should read up on:
* [Home Assistant theming](https://www.home-assistant.io/integrations/frontend/#defining-themes)
* [card-mod lovelace plugin](https://github.com/thomasloven/lovelace-card-mod/)

That should answer both cases more in depth and give you the information you need on how to deal with styling and theming lovelace + custom cards
