### ISSUE TITLE
Feature Request: programmable custom action button

### ISSUE THREAD

**Issue by valantur** [nervetattoo/simple-thermostat#109]
Hi and thank you for this awesome Lovelace card! 

I'm an Ecobee user, and the only thing I noticed I can't do from this card is setting my thermostat to resume the existing program. I can click on the Home preset, but that's not the same as resuming the program. My Ecobee is set to keep a preset hold indefinitely (for various reasons) so if I choose the Home preset it will stay like that forever. What I'd like to do instead is to tell the Ecobee that it should resume the schedule instead.

There's already a service you can call on Home Assistant that does exactly that (ecobee.resume_program) so I wonder if you could add an option for a custom preset button (or a custom button somewhere else on the card) that people can program to fire the service they want.

Does that make sense?

Thanks for considering it. I've no idea how hard it would be to implement this.

**Comment by jhonathas** [comment]
I came to find out exactly if there was a way to do this. In my case I wanted to put a button to turn off the light of an LG that I own. Did you get something?

**Comment by valantur** [comment]
@jhonathas nope... I'm still hoping it will get implemented at some point.

**Comment by Vxider** [comment]
Vote for this feature, it is used to execute some scripts or call some services. I temporarily add some buttons for scripts by using `button-card`.
<img width="462" alt="截屏2020-08-03 01 10 21" src="https://user-images.githubusercontent.com/6134315/89128182-6482f900-d526-11ea-95b9-feb50b8d3de3.png">

**Comment by nervetattoo** [comment]
I would say just use button card. Having this type of feature duplicated across _all the cards_ is a bit of a waste. Whatever is added would be lacking a lot compared to button-card.
