### ISSUE TITLE
Temp and state not translated

### ISSUE THREAD

**Issue by jrnhrmn** [nervetattoo/simple-thermostat#110]
When I switch to Dutch everything is translated but **Temperature and State**.

**Comment by Misiu** [comment]
@jrnhrmn https://github.com/nervetattoo/simple-thermostat#available-configuration-options
take look at label: `temperature` and `state`.
This should be possible.

**Comment by jrnhrmn** [comment]
> @jrnhrmn https://github.com/nervetattoo/simple-thermostat#available-configuration-options
> take look at label: `temperature` and `state`.
> This should be possible.

Thanks. Looks like what I was looking for.
