### ISSUE TITLE
Icon only shows up when name is enabled

### ISSUE THREAD

**Issue by onimoschta** [nervetattoo/simple-thermostat#114]
I want to use an icon instead of a name for my thermostat.
when i use the syntax `name: false` it makes both disappear. When I enable the name the icon is displayed but i only want the icon to show up. Is there a workaround?

**Comment by nervetattoo** [comment]
No workaround. Feel free to create a PR!

**Comment by tomvanswam** [comment]
No longer relevant with config change implemented with commit ed1be99.
The `name: false` is removed, in favour of `show_header: true`.
Setting 
```yaml
show_header: true
name: ' '
```
Will show an icon, but no name, as @onimoschta requested
