### ISSUE TITLE
Doesnt display on Edge

### ISSUE THREAD

**Issue by Dave-Bryant** [nervetattoo/simple-thermostat#115]
My simple-thermostat works fine on IOS & Chrome. But it doesn't work on Edge. I get a message 'Custom element doesn't exist: simple-thermostat'. In the log I find Logger: frontend.js.latest.202002205 First occured: 4:01:38 PM (1 occurences) Last logged: 4:01:38 PM 
http://hassio.local:8123/frontend_latest/chunk.7630cd249b983c27a4ae.js:2089:2753 Expected '('
I have Installed: Simple-Thermostat version 0.34.1
Config details are:  
arch | armv7l
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Australia/Sydney
version | 0.106.5
virtualenv | false

My lovelace is very basic i.e. 
-entity: climate.study
   type: 'custom:simple-thermostat'

Does anyone have any thoughts?

**Comment by nervetattoo** [comment]
I don't have access to Edge. Is this still a problem?
