### ISSUE TITLE
Floating point precision problem

### ISSUE THREAD

**Issue by rslite** [nervetattoo/simple-thermostat#117]
Very useful card. I have a problem though. I use a small step size of 0.1 for my custom thermostat. When the target values are incremented they will sometimes be 22.3000000001 or 23.6999999998 and isEqual will never return true, thus _updatingValues is never set to false. Is there an elegant generic way to fix that?

**Comment by nervetattoo** [comment]
I guess casting numbers to a string with `toFixed(decimals)` might be the easiest way. I'd guess the HA service would work equally well with strings as numbers. The number of decimals to use for toFixed could be decided by inspecting if step_size is between thresholds like `>= 0.1 && < 1`. It sounds like you've looked into the code for a solution, so do you want to look into creating a PR for it?

**Comment by rslite** [comment]
My javascript is pretty rusty, but a method that worked for me was to "normalize" the values before they are put in the values object and when they are incremented/decremented (when the user clicks the buttons). IMHO I think it would be easier to keep the values numeric. If you would be OK with that I could work on a PR (I haven't done one so far, so might take me a while to figure out how).

function normalize(val) {
	return Math.round(val*100)/100
}
