### ISSUE TITLE
Up/Down arrow no longer showing

### ISSUE THREAD

**Issue by reesion** [nervetattoo/simple-thermostat#127]
Hi,

After updating to v0.110.0, the up/down arrow no longer shows up.

![image](https://user-images.githubusercontent.com/53692597/82516721-d15d3880-9b5e-11ea-9549-3fe9c43af761.png)

**Comment by nickdos** [comment]
I'm also seeing the same thing. My settings were for compact mode using the "plus" and "minus" buttons and they no longer show up.

**Comment by sm0keKings** [comment]
I am having the same issue too. 
![image](https://user-images.githubusercontent.com/61777651/82523883-beebfa80-9b70-11ea-937c-5c5ff1d96a22.png)

**Comment by gitrummy** [comment]
+1

**Comment by lalexdotcom** [comment]
Same here

**Comment by jccshmny** [comment]
+1

**Comment by mobilemutex** [comment]
Replacing all (4) paper-icon-button with ha-icon-button in simple-thermostat.js seems to work for me.

**Comment by Idanit** [comment]
Issue already open: https://github.com/nervetattoo/simple-thermostat/issues/123

**Comment by DrJohnT** [comment]
Same here

**Comment by RyanWoirol** [comment]
Same

**Comment by jleach87** [comment]
+1

**Comment by Fabenissimo** [comment]
> Replacing all (4) paper-icon-button with ha-icon-button in simple-thermostat.js seems to work for me.
> 
> Edit: As per these changes: [home-assistant/frontend@0a92c28#diff-873f41cce3df4d28dd685519a4e87d01L135](https://github.com/home-assistant/frontend/commit/0a92c28bac80a0bddc3f54577fc62670f3974c15#diff-873f41cce3df4d28dd685519a4e87d01L135)

Anyone had luck with this? I've replaced the 4 occurrences, readded it to my lovelace resources, reloaded the page several times, restarted HA, deleted my browser cache several times, still no icons...

**Comment by reesion** [comment]
> Anyone had luck with this? I've replaced the 4 occurrences, readded it to my lovelace resources, reloaded the page several times, restarted HA, deleted my browser cache several times, still no icons...

Doesn’t work for me either

**Comment by jccshmny** [comment]
> Anyone had luck with this? I've replaced the 4 occurrences, readded it to my lovelace resources, reloaded the page several times, restarted HA, deleted my browser cache several times, still no icons...

Didn't work for me.

**Comment by mobilemutex** [comment]
> > Replacing all (4) paper-icon-button with ha-icon-button in simple-thermostat.js seems to work for me.
> > Edit: As per these changes: [home-assistant/frontend@0a92c28#diff-873f41cce3df4d28dd685519a4e87d01L135](https://github.com/home-assistant/frontend/commit/0a92c28bac80a0bddc3f54577fc62670f3974c15#diff-873f41cce3df4d28dd685519a4e87d01L135)
> 
> Anyone had luck with this? I've replaced the 4 occurrences, readded it to my lovelace resources, reloaded the page several times, restarted HA, deleted my browser cache several times, still no icons...

You need to delete the simple-thermostat.gz file. Hacs will serve the browser the gz file if it’s there in order to save bandwidth. If it’s not there, it will use the .js file

**Comment by DrJohnT** [comment]
> You need to delete the simple-thermostat.gz file. Hacs will serve the browser the gz file if it’s there in order to save bandwidth. If it’s not there, it will use the .js file

Tried it and did not work.  Reinstalled component several times too.  Icon still missing

**Comment by technerd88** [comment]
Updating the icons and deleting simple-thermostat.gz corrected the issue.

**Comment by reesion** [comment]
Updating to the latest release fixes the issue.

**Comment by Yonny24** [comment]
Thanks guys. Fixed that now.
