### ISSUE TITLE
unable to install 

### ISSUE THREAD

**Issue by GHSTUDIO1** [nervetattoo/simple-thermostat#130]
I used HACS to install simple-thermostat and I see "simple-thermostat" in www/community.....it also shows up in lovelace resources...so it looks like it is installed correctly....but apparently not.

I am unable to find that card to add it to my lovelace overview.  I then tried using the standard thermostat and editing it to point to simple-thermostat instead of thermostat, but got an error. 

Why doesn't it install correctly (latest HACS/latest HAAS)...what am I doing wrong?

**Comment by Linwood-F** [comment]
I just tried as well, and cannot get it to work (ha 0.110).

**Comment by klejejs** [comment]
I have HA 0.110 and just installed it using HACS without any problems. Everything is working.

**Comment by Linwood-F** [comment]
I found my issue.

The documentation has old info for the addition of the js module, referring to where it went in the UI config, but it now goes into the configuration.yaml, and refers to it by hacsfiles instead of local.  When I did it, I neglected to add the second level folder.  The right entry is: 

```
lovelace:
    mode: yaml
    resources:
      - url: /hacsfiles/simple-thermostat/simple-thermostat.js?v=1
        type: module

```
I left off the seemingly extra simple-thermostat in the path.  With the above it worked fine.

Thank you for giving me the motivation to try again.

Not sure if this applies to @GHSTUDIO1 or not, but in terms of an issue, it would probably be helpful to update the documentation for hacs install.

Thank you @klejejs

**Comment by turnmike2** [comment]
Hi, 
Perhaps I am making a mistake. Using HACS  (on 0.110.2) also. 
I thought the url editing should also be possible through: 
"Configuration/lovelace dashboards"

With the installation the file is placed in the following directory:
/config/www/community/simple-thermostat/simple-thermostat.js

But every combination I used through the lovelace automatic mode does not seem to do the trick.
(eg /local/simple-thermostat/simple-thermostat.js?v=1)
So, is yaml mode the only possibility? Or am I doing something wrong?

**Comment by GHSTUDIO1** [comment]
same as turnmike2...I can not configure through the configuration/lovelace dashboard...only by manually editing the yaml code myself.  I now have it working, but it does not show up as a card option using the configuration/lovelace dashboard.

**Comment by turnmike2** [comment]
Ok. I found my culprit.
The example to add is a bit misleading. 
The path in the "lovelace dashboards" should be:

/local/community/simple-thermostat/simple-thermostat.js?v=1
(as this is the place the js file is placed)

**Comment by GHSTUDIO1** [comment]
I tried to add the resource using that address and it didn't help...still does not show up as a selectable card.  Then, since it is in the exact same folder (www) as two other resources that I already added, I changed the entry to: /hacsfiles/simple-thermostat/simple-thermostat.js  which is the format for the other two resources and simple-thermostat still isn't a selectable card.  

I have the card working, however coded it in yaml...but it should show up as a selectable card.

**Comment by Linwood-F** [comment]
The "local" vs "hacsfiles" was a fairly recent change (couple of months) and I do not think they have removed support for "local".   But if using hacs then hacsfiles is correct.

I cannot comment on the UI based configuration of lovelace, I have not tried it since I already had so much yaml.

**Comment by Linwood-F** [comment]
Postscript to above: I remembered I could also set up a GUI configured dashboard, so did.  You are right, the simple-thermostat does not appear automatically, but then again I didn't see any custom entities there.  Are you sure custom entities are supposed to appear?   

I did a manual add, put in my yaml, and it worked great though.  So you can write the yaml in a GUI configured dashboard.

**Comment by m4rkireland** [comment]
I also had this while installing via HACS.  It seems that the `?v=1` parameter is missed off when it is added into the Lovelace Dashboards > Resources list.

Adding the `?v=1` manually fixed this, so I was able to create a manual card within the GUI.

![image](https://user-images.githubusercontent.com/11231797/91639151-8f207e80-ea0c-11ea-8c66-6e56882ae343.png)

![image](https://user-images.githubusercontent.com/11231797/91639171-b4ad8800-ea0c-11ea-8a0e-b94adea155e6.png)

**Comment by chilicheech** [comment]
@ m4rkireland's solution worked for me as well. What's weird is that I have 2 other cards I installed from HACS that work just fine without the `?v=1`
<img width="1175" alt="Screen Shot 2020-09-08 at 1 35 10 PM" src="https://user-images.githubusercontent.com/732659/92525162-31dcb800-f1d8-11ea-849d-0190f77b2e54.png">
