### ISSUE TITLE
Request: If the thermostat state is off, hide the set point controls

### ISSUE THREAD

**Issue by tmchow** [nervetattoo/simple-thermostat#131]
If the thermostat is off, I think it's better to not show the set point controls at all. Right now it defaults to "N/A" which is a little odd:

![image](https://user-images.githubusercontent.com/517103/82770429-6d9c6f00-9ded-11ea-9321-ee8f9dcae6ee.png)

Closest thing I've got it just specifying:

```
fallback: ''
```

which gets:
![image](https://user-images.githubusercontent.com/517103/82770425-670df780-9ded-11ea-87d1-5fbe27280541.png)

I think it would be far better to remove the set point display and controls until the state is in a mode other than "off":

![image](https://user-images.githubusercontent.com/517103/82770539-c10ebd00-9ded-11ea-8738-b1a7cae300c3.png)

**Comment by rb-26** [comment]
An option to disable it altogether would be appreciated as well.

**Comment by htmltiger** [comment]
Please add option to disable set temperature as I want to use the button rows only for other purpose.
Thank you.

**Comment by nervetattoo** [comment]
I use generic thermostats and I can change setpoints when in off mode so it would be weird to hide the controls as the changes then are actually used. 
If someone wants to add more elaborate support where it detects if set points are configurable to decide if the controls show that would be cool, but its not something I will do. Closing as no one has submitted a PR in half a year anyway 😸
