### ISSUE TITLE
state specific icons issue

### ISSUE THREAD

**Issue by ktownsend-personal** [nervetattoo/simple-thermostat#132]
I don't know if the states used for the state specific icons (idle, cooling, heating) differ by device or regionally, or if this is a bug, but I had to use "cooling" instead of "cool" for the state driven icon to appear for that state. The defaults were already not working for the cooling state, so I suspect this is at least partially a bug. If the states can vary by device or by region, the default operation may need to detect that somehow so that the default icons are functional, and the documentation should indicate that the values may vary depending on the climate device or region.

**Comment by loongyh** [comment]
Indeed, I have to put in the below config for the icon to show up during the cooling state:
```
icon:
  cooling: mdi:radiator
  idle: mdi:radiator-disabled
  'off': mdi:radiator-off
```

**Comment by nervetattoo** [comment]
It can differ for the device type. Regardless cooling is a bug. It should be a not too difficult fix if someone wants to get their hands dirty.

**Comment by tomvanswam** [comment]
I'd like to volunteer to get my hands dirty.

Just a couple of questions.
Why is `cooling` a bug? The `hvac_action` for heating is also `heating` and not `heat`?
My airconditioning units do not have this attribute. Is it ok to use the state as fallback for icon selection?

**Comment by nervetattoo** [comment]
A bug if a state from HA is not mapped to an icon in the card. Ideally they should all be mapped to defaults. Long time since I looked at those as I don't show icons myself, so sounds very likely that they are out of sync.

**Comment by tomvanswam** [comment]
Great I'll check what the states in HA are and add defaults for those
