### ISSUE TITLE
HACS says not loaded but card works?

### ISSUE THREAD

**Issue by caro7372** [nervetattoo/simple-thermostat#135]
Hi,

in HACS it says card not loaded.
(Information
Not loaded in Lovelace
You have 1 Lovelace elements that are not loaded properly in Lovelace.)

When I check it I see the next picture.
![image](https://user-images.githubusercontent.com/63898040/84408839-edf40a00-ac0c-11ea-91da-49bb35cad96a.png)

I can not load it again.

Regards,

Robert

**Comment by Linwood-F** [comment]
Same issue here, I don't know if it is a false alert, or something subtle is not working.  I also get it on mini-media-player, and there (whether because of this or otherwise) some icons are not working.

**Comment by caro7372** [comment]
Okay,

I found out where the problem is.
If you have also other cards, look at the adress compared to this one.
I changed to /hacsfiles/ .............

Then it loaded oke.

![image](https://user-images.githubusercontent.com/63898040/85362376-8b5d1100-b51e-11ea-9eba-e81eee2744f3.png)

**Comment by Linwood-F** [comment]
That is not my problem, at least it does not appear to be.  I use YAML and have mine configured as all the other HACS modules, and it says it won't load though it functions.  Mine look like this (only the last few, I have quite a lot): 

```
      - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
        type: module 
      - url: /hacsfiles/mini-media-player/mini-media-player.js?v=1.9.1
        type: module
      - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
        type: module
      - url: /hacsfiles/ext-weblink/ext-weblink.js
        type: module
      - url: /hacsfiles/simple-thermostat/simple-thermostat.js?v=1.1.1
        type: module

```
Changing the version number has no impact.  Looking at the folder structure in SSH and they all look identical, same protections, same ownership.  I no longer have any reference in the UI yaml only configuration.yaml.   And as mentioned -- it does work fine.

The image at the bottom of your posting, @caro7372 , is difficult to read, but is that a snippet from a GUI somewhere?  Where did you make the change?

**Comment by caro7372** [comment]
Yes,

In the configuration / LoveLace Dashboards.
Then in sources.

So I do not have it in de yaml itself.

Regards,

Robert

**Comment by Linwood-F** [comment]
Yes, now that I look I can see it there, but not change it.  But it appears there correctly.  Maybe there's something that keeps this from working right with yaml configuration mode.

**Comment by Linwood-F** [comment]
OK, my mini-media-player failed because of a change of file name (for the .js not the path). Reinstalling showed the proper name.  When I fixed mini-media-player, the problem with simple-thermostat went away, without other change to it.  Not sure what that means, but at least I have no failures now.

**Comment by caro7372** [comment]
Hi,

great job! Good to know that we can fix our problems.
Thank you for keeping me updated so I could learn from you ( your problem ) too.

Met vriendelijke groet / Kind regards,
 
Robert Golz
