### ISSUE TITLE
Hide titles for sensors

### ISSUE THREAD

**Issue by martinjuhasz** [nervetattoo/simple-thermostat#136]
Is there a way to hide titles for sensors?
On default mode, you can hide the "Temperature" title by using the "hide" property, but this will also hide the "current temperature" sensor reading.

What i would like is something like this:
<img width="336" alt="Screenshot 2020-06-15 at 23 21 14" src="https://user-images.githubusercontent.com/204190/84707706-7a7d3000-af5f-11ea-8c39-ecff6a0af9ea.png">
Is this possible somehow?

**Comment by rengaboy** [comment]
I have the same question. Maybe it's possible to add temperature_title, state_title and icon_title options to configuration?

**Comment by nervetattoo** [comment]
I guess you could do:
```yaml
label:
  temperature: ''
  state: ''
```

The html element will still be there and use some space I guess, but the text should be gone
