### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tborychowski** [nervetattoo/simple-thermostat#143]
Allow styling different states.
E.g.: I'd like to highlight (in a different color) when my thermostat is "heating" (vs "idle").

I could do this with the custom css plugin, but the only difference between these 2 states is the word inside a classless div...

**Comment by nervetattoo** [comment]
The `<ha-card>` element has the current action as a class. So `.heating` or `.off` etc. Should be sufficient to hack customised styling imo.
