### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by AlBrough** [nervetattoo/simple-thermostat#145]
Is there a possibility that you could add decimal/factor correction?
I have a controller that reports 10 times the actual value, as it seems to ignore the decimal point. As an example, it reads 166° when it should be 16.6° and the same for setpoint temperature, 13° when it should be 1.3°.
I have created sensors in my config that fix this for my dashboard by dividing the values by 10 but I am not sure how to feed them into this card as I can't adjust the values with a sensor value.

Thanks for the plugin, it does exactly what it says it will and it was so easy to integrate!

**Comment by AlBrough** [comment]
This will help anyone integrating Inkbird Wifi controllers

**Comment by nervetattoo** [comment]
No, that needs to be fixed in the integration as it messes with everything you build around that thermostat (automations, templates).
