### ISSUE TITLE
Not compatibility with Netatmo Thermostat

### ISSUE THREAD

**Issue by vampirete** [nervetattoo/simple-thermostat#149]
Hi.
This frontend isn't to compatibility with netatmo thermostat because now the integration netatmo use webhook for to communicate with netatmo.

**Comment by JensNikolajOlsen** [comment]
Any solution to this?

**Comment by nervetattoo** [comment]
This card aims to support HA climate devices through the HA services and state. If netatmo works differently (I don't own one) then someone who owns an device is free to submit a PR.
Closing the issue  as its not actionable or something I will work on, feel free to reopen with more context or as part of doing a PR.
