### ISSUE TITLE
Feature: allow hiding the `Operation` text

### ISSUE THREAD

**Issue by chilicheech** [nervetattoo/simple-thermostat#152]
It would be awesome if we could give the `Operation` text. When we look at the button and see the labels we know they mean operation and we can reclaim some real estate be getting rid of the operation label.

Cheers

**Comment by nickneos** [comment]
+1 for this. 

Maybe even get rid of "off" as welland just have each operation (eg. cool, heat, etc) toggle on/of with each press.

**Comment by nervetattoo** [comment]
```yaml
control:
  _names: false
```
