### ISSUE TITLE
Error mobile application

### ISSUE THREAD

**Issue by inosen** [nervetattoo/simple-thermostat#157]
When I try to see t my panel with smartPhone I always see that.
![Screenshot_20200920_131510_io homeassistant companion android](https://user-images.githubusercontent.com/71597230/93713293-2172f880-fb5b-11ea-90d2-5ec673436a8b.jpg)

But in Desktop I haven't problem.

**Comment by kammmuschel** [comment]
Same issue, it works on Chrome Desktop, not on the iPhone app

**Comment by kammmuschel** [comment]
Now it works for me on iPhone Safari and Chrome - but still not on the app. Is this a caching issue?

**Comment by kammmuschel** [comment]
Ok. In the app under app settings the second from the bottom: reset frontend cache. Then reload the page. That fixed it for me.
