### ISSUE TITLE
Is it possible for me to create a custom button pointing to a switch or light?

### ISSUE THREAD

**Issue by jhonathas** [nervetattoo/simple-thermostat#158]
I would like to be able to customize a button together with the existing function buttons. This button would be associated with a switch or light already created in my Home Assistant.

I put an example below ...

![image](https://user-images.githubusercontent.com/28179/93713818-caf2c380-fb34-11ea-8458-87ff768109e4.png)

**Comment by nervetattoo** [comment]
Not possible and not something I want to add, its outside of the scope of the card. Just use a button card stacked with the thermostat.
