### ISSUE TITLE
Unable to create own Modes

### ISSUE THREAD

**Issue by MiguelESP89** [nervetattoo/simple-thermostat#161]
Hey i want to creat my hvac modes but it is not possible to show. 
The card shows always the "auto" label

here ist my code: 

![Bildschirmfoto 2020-10-09 um 12 06 43](https://user-images.githubusercontent.com/39128034/95570899-e7916580-0a27-11eb-9ead-ec47d8fa9644.png)

is it my fault or a problem with the card?

Thank you for the help. 

Regards
Miguel

**Comment by nervetattoo** [comment]
You can't create custom modes. You only control which of the modes in HA is actually shown in the card, this is to be able to hide modes you never use.
