### ISSUE TITLE
Card not loading properly

### ISSUE THREAD

**Issue by Sethenor** [nervetattoo/simple-thermostat#162]
I'm having some issues with this custom card in home assistant 0.116 and also in 0.116.1. I've tracked it down to this because the default thermostat card works fine. Simple-thermostat version installed is 0.36.0, also tried reinstalling the card but that didn't help.

What happens is that when I open HA for the first time the simple thermostat card doesn't show. When I go to Edit Dashboard it suddenly shows up in the editor and if I close the editor it still shows like it's supposed to.
If I close the HA tab in my browser or the app and open it again, the card is gone again.

On first opening HA in my browser (cache etc has been cleared several times) it shows this in Inspect Element:
![2020-10-09_18-44-45_vivaldi](https://user-images.githubusercontent.com/2983567/95609770-93a27300-0a5f-11eb-9a12-6fcf39a21f26.png)
note: "hui-thermostat-card" is the default one from HA which loads fine.

If I remove the "display: none;" it shows the default Custom element doesn't exist: simple-thermostat.
![2020-10-09_18-46-28_vivaldi](https://user-images.githubusercontent.com/2983567/95609915-c77d9880-0a5f-11eb-9b13-f328ca0009a5.png)

**Comment by bg1000** [comment]
I am seeing this same issue with Home Assistant .116.1 and .116.2

**Comment by quinten94b** [comment]
Same issue. getting the report that custom element doesn't exist
Version 116.2 running on Pi4 and HassOS 4.13

**Comment by LukasQ** [comment]
same here

**Comment by giglagla** [comment]
Same here using Chrome (version 86.0.4240.75) and the mobile App.
Seems to work well with Firefox (version 81.0.2)

Home Assistant 116.2 running on HassOS 4.13

**Comment by krelltunez** [comment]
Phew!  This was driving me crazy.  I've seen it in Chrome and in the app on Android.  Same exact behavior.  I'm running 0.116.4.

**Comment by paulhobbel** [comment]
Just updated to from 0.115 ->0.116.4 and can confirm it's no longer loading unless I hit edit or resize the screen. This is probably an issue in HA itself. Will create an issue for it

**Comment by bg1000** [comment]
@paulhobbel - There was a breaking change for custom cards in 116.  The change and the workaround is documented here - https://developers.home-assistant.io/blog/2020/10/02/lazymoreinfo/.

**Comment by Sethenor** [comment]
0.117 fixed the issue for me it seems, not sure if it's temporary or permanent, but just letting you know.

**Comment by giglagla** [comment]
> 
> 
> 0.117 fixed the issue for me it seems, not sure if it's temporary or permanent, but just letting you know.

Same here

**Comment by quinten94b** [comment]
> > 0.117 fixed the issue for me it seems, not sure if it's temporary or permanent, but just letting you know.
> 
> Same here

issue is still there for me, after update to 0.117

**Comment by giglagla** [comment]
> 
> 
> > > 0.117 fixed the issue for me it seems, not sure if it's temporary or permanent, but just letting you know.
> > 
> > 
> > Same here
> 
> issue is still there for me, after update to 0.117

Are you using the last card version ?

**Comment by paulhobbel** [comment]
Yes this issue was solved here https://github.com/home-assistant/frontend/pull/7407

**Comment by quinten94b** [comment]
> > > > 0.117 fixed the issue for me it seems, not sure if it's temporary or permanent, but just letting you know.
> > > 
> > > 
> > > Same here
> > 
> > 
> > issue is still there for me, after update to 0.117
> 
> Are you using the last card version ?

Yes, I even uninstalled the card from HACS and reïnstalled it.
It keeps giving me the error that the simple thermostat card does not exist.

But it's there in the files and all my other custom cards work without problems.

**Comment by giglagla** [comment]
> 
> 
> > > > > 0.117 fixed the issue for me it seems, not sure if it's temporary or permanent, but just letting you know.
> > > > 
> > > > 
> > > > Same here
> > > 
> > > 
> > > issue is still there for me, after update to 0.117
> > 
> > 
> > Are you using the last card version ?
> 
> Yes, I even uninstalled the card from HACS and reïnstalled it.
> It keeps giving me the error that the simple thermostat card does not exist.
> 
> But it's there in the files and all my other custom cards work without problems.

Had the same issue this morning after updating HACS cards. 
I resolved it by deleting a duplicate resources (was in /local AND in /hacsfile).
I don't remember which one it was.

**Comment by nervetattoo** [comment]
Should be fixed and I can't replicate anymore in the app so closing.
