### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by agneevX** [nervetattoo/simple-thermostat#163]
Hi,

I have the default font set, yet I'm seeing a different, very thin font, unlike the top 2 images in your README.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/19761269/96226062-b2e55700-0faf-11eb-9883-31d02eba75e0.png">

Is there a way to change this font to the default font used by Home Assistant? Thanks!

**Comment by nervetattoo** [comment]
The card does not set its own font it only uses HA defaults. Only font size and for sensor headings also font weight is set.

**Comment by agneevX** [comment]
Can the font weight be changed, because it looks too thin??
