### ISSUE TITLE
How to display set number of decimals for sensors

### ISSUE THREAD

**Issue by setdetnet** [nervetattoo/simple-thermostat#165]
Where sensors are a fraction value such as "0.123" , "10.01" , "0.000003" whatever - is it possible to force the displayed value to be of a specific pattern type , i.e. "##.###" would provide a fraction with 5 significant digits including 3 mantissa digits.
Or, perhaps at least some way of specifying decimals, as in **decimals: 3**.
?

Forcing the sensor to be modified for example using a **value_template** is not good design practice because the real value is being manipulated for display purposes. Good design practice is to manipulate the display value not the underlying real value.

**Comment by nervetattoo** [comment]
Good idea. It makes sense to offer the same number formatting as the setpoint uses (so decimals: 3). Will add it to the list of things I plan to happen.

**Comment by setdetnet** [comment]
Great 👌
