### ISSUE TITLE
Setpoint arrows not being rendered on mobile app.

### ISSUE THREAD

**Issue by setdetnet** [nervetattoo/simple-thermostat#166]
The ^ and v arrows on the setpoint value (or < and > if using row layout) are rendered on the PC/web browser, but are not being rendered in Home Assistant app. This seems to have been broken by HA new releases because this happened when I upgraded to HA version 0.116.

**Comment by nervetattoo** [comment]
Should be fixed in 0.117 and I can't replicate anymore in the app so closing.
