### ISSUE TITLE
Updater not working

### ISSUE THREAD

**Issue by Diondk** [nervetattoo/simple-thermostat#17]
Hi,

since yesterday evening my simple-thermostat card stopped working, i checked the open issues and found the Custome element doesn't exist threat. i tried to update the thermostat card with the auto updater. 

But when opening the URL i get a 404: not found. 

https://raw.githubusercontent.com/nervetattoo/simple-thermostat/allow-updates/tracker.json

Can you please help me?

Kind regards,
Dion

**Comment by nervetattoo** [comment]
There was an error with that URL in the README. The correct URL is https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json and the README is now fixed. Sorry for the inconvenience!
