### ISSUE TITLE
no way to replace unit of measurment shown.

### ISSUE THREAD

**Issue by docsparks** [nervetattoo/simple-thermostat#173]
Understandably the nature of this control is to be used as thermostat but due to its flexibility and wonderful looks, ive seen it used a humidifier controller and dehumidifier controller and a CO2 controller.

I have searched in all source code and cant pinpoint where the main temperature shown is inheriting its unit of measurement.   For example even with all attributes of 'unit' being changed, My temperature shown on the main label carries the '°F' and regardless if i customized my climate entitiy within homeassistant, simple-thermostat card brings '°F' into it. 

Ive seen another person have their main label show % and have the ST used as a humidity controller but thats not my use case and can only assume its inheriting its parent control.

`type: 'custom:simple-thermostat'
entity: climate.tstat
attribute: null
unit: T
sensors:
  - entity: climate.tstat
    attribute: temperature
    unit: ' x1'
  - attribute: temperature
    unit: ' x2'
  - attribute: current_temperature
    name: ctemp
    unit: ' x3'
  - attribute: current_humidity
    name: Humidity
    unit: ' x4'
step_layout: row
decimals: 0
label:
  temperature: temp
name: true
control:
  _names: true
  _headings: true
  _icon: true
  hvac:
    cool:
      - attribute: null
        unit: ' x5'
style: |
  ha-card {
    --st-font-size-xl: 32px;
    --st-font-size-m: 00px;
    --st-font-size-title: 14px;
    --st-font-size-sensors: 13px;
    --st-spacing: 3px;
    
  }`

any null lines were inserted via homeassistant while trying to use the sub measurement types below attribute values.   

my temperature labels and humidity labels on the left side are correct except for the first one above 'state' and the main label that we see as the larger font in the UI.

I have discovered I can hide the unit of measurement with changing the style 'st-font-size-m' to 0 but i would like to show 'PPM' or 'Gigawatts' just because.  

If anyone is aware of the point in the coding that I can add a string replace, id accept that as well.   Im not even close to ready for javascript. 
Thanks.

**Comment by docsparks** [comment]
i have found the usage of units used in the javascript but after a few hours of trying to understand installing a handful of things to my VSC ide i couldn't figure out how to build from source and will leave it to you pros.  thank you!

**Comment by nervetattoo** [comment]
Will soon support setting `unit: whatever` and `unit: false` on the top level config for the thermostat.
