### ISSUE TITLE
more of a question

### ISSUE THREAD

**Issue by tlmarion** [nervetattoo/simple-thermostat#175]
The main number that is in between the step buttons.. Where is your card pulling that from? How can I customize the data for it.

**Comment by Ruco** [comment]
I have a related question. Seeing as your question is talking about what's called, AFAIK, the `setpoint`.
But I am unable to hide it, even though the documentation says it is possible. Using the `hide` configuration option.

I am trying to create a card which only shows the preset buttons.

Amazing custom card btw. So much better than the default.

**Comment by nervetattoo** [comment]
You can hide it in 2.x by doing
```yaml
setpoints: false
```

@tlmarion It is provided from the entity as an attribute, most often named `temperature`. I'm not sure how you want to customize it? That would be at the climate integration level really
