### ISSUE TITLE
Change in away temperature is not remembered

### ISSUE THREAD

**Issue by baunan** [nervetattoo/simple-thermostat#176]
Hi,
Thanks for a great card. I am using it together with HA generic thermostat for all my rooms. I noticed a small issue, if the away temperature is changed then it is not stored. Example, if I change the default away temperature in this case 16 degC to e.g. 15 on the card and switch to home mode and then back then it will show the default temperature from Generic Thermostat of 16 degC. However if I do the same with the home temperature which is set to 22.5 and change it to 24 and switch to away mode and back, then the adjusted temperature of 24 is remembered. Should really liked to have the same behavior for the the away temperature.

Not sure if this is something with this card or an underlying problem with HA's generic thermostat.

![image](https://user-images.githubusercontent.com/59838425/99293836-7b362d00-2843-11eb-8f43-d97686624277.png)
![image](https://user-images.githubusercontent.com/59838425/99294786-d1f03680-2844-11eb-9341-9dd2c3a0dd59.png)

**Comment by nervetattoo** [comment]
Underlying. Perhaps setting `away_temp: 16` forces it, try to remove it?
