### ISSUE TITLE
Resize "state" combobox

### ISSUE THREAD

**Issue by robertotucci** [nervetattoo/simple-thermostat#18]
Hi,
In my card, i can see the state "Spento" (is equal to "off" in english language) but the field is not large enough and the text is truncated.
Can you fix this please?

![image](https://user-images.githubusercontent.com/923058/51338686-c554f880-1a8a-11e9-81ca-a8cc78e0eba6.png)

Thanks

**Comment by nervetattoo** [comment]
In 0.17 modes was moved from a dropdown to buttons, should solve this.
