### ISSUE TITLE
 preset-modes issue

### ISSUE THREAD

**Issue by abm-Github** [nervetattoo/simple-thermostat#184]
Hello, I am new in home-assistant and not a software specialist.
Can someone please help me, I've been looking for several days now to solve my problem.
In fact, I would like to create this card

![image](https://user-images.githubusercontent.com/60431720/100886330-ff2f1c80-34b3-11eb-8f27-1c35179895a9.png)

For that, my configuration for the /config/climates.yaml is:

![image](https://user-images.githubusercontent.com/60431720/100886443-2259cc00-34b4-11eb-803a-879e35a9e42b.png)

 I installed the module simple thermostat like that

![image](https://user-images.githubusercontent.com/60431720/100886510-39002300-34b4-11eb-8a96-4f55e6257152.png)

![image](https://user-images.githubusercontent.com/60431720/100886531-3f8e9a80-34b4-11eb-8e9c-da97b3876a14.png)

Finally my config for the card, and as you can see below, I don’t have what I want to obtain.
I don't understand what's going on, did I forget something?
Thank you in advance for whoever can give me the answer.

![image](https://user-images.githubusercontent.com/60431720/100886589-4d442000-34b4-11eb-82c4-8b3e8ed66f13.png)

**Comment by abm-Github** [comment]
do I need to install an addon via HACS?

**Comment by DeltaAngle** [comment]
Generic thermostat will not support modes like in your example picture. From your configuration, it appears your thermostat is connected to HA via MQTT. You can try to setup your climate component via the [MQTT HVAC integration](https://www.home-assistant.io/integrations/climate.mqtt/). MQTT HVAC supports modes which should work this card, but you have to make sure your device actually supports the modes. Review the details on the MQTT HVAC documentation linked above to determine how to configure the component properly.

**Comment by abm-Github** [comment]
Thank you for your prompt response
For information, I don't have an mqtt thermostat, I made my own system with Node Red, an arduino and a specific electronic control board (control of 8 radiators).
But your answer is very clear, and I think I know how to proceed.
Thanks again for your help.
