### ISSUE TITLE
Issue - Hiding thermostat name

### ISSUE THREAD

**Issue by smugleafdev** [nervetattoo/simple-thermostat#187]
From the documentation: `hide_header bool: Set to false to hide card name and icon`

This doesn't seem to be working. I've been using: `name: false` which works and hides both the name and the icon.

But also, because HA sees "name:" and thinks it needs a string, every time I open up the code editor it has changed to: `name: 'false'` This is annoying because it happens 100% of the time I click "SAVE" in the editor.

**Comment by tomvanswam** [comment]
The README is wrong here. You should use show_header : true/false
A PR is already there to fix this: #182

**Comment by smugleafdev** [comment]
Uh-oh. Is it supposed to lose all padding on the top?

![Padding gone](https://i.imgur.com/05bAfKH.png)

**Comment by tomvanswam** [comment]
No it isn't. However the same pr fixes that as well.

**Comment by smugleafdev** [comment]
Thanks for the info!
