### ISSUE TITLE
Temp/State labels cannot be hidden

### ISSUE THREAD

**Issue by smugleafdev** [nervetattoo/simple-thermostat#189]
The temp and state labels cannot be hidden while leaving their values visible.

![Example empty label](https://i.imgur.com/udGCVXR.png)

A followup problem is that currently, if the temp label _was_ hidden, it wouldn't be clear to the user what it represents (state is happy to not have a label though; it's pretty clear what ["Idle - Home" or "Heating - Away"](https://github.com/nervetattoo/simple-thermostat/issues/190) means). The default HA thermostat card solves this issue by having the two numbers stacked, and the set temp much smaller, at the cost of making the entire card much larger.

Maybe ditching the labels and putting the current temp on the same line as the state would be a simple solution?

![Example solution](https://i.imgur.com/iOxyTqE.png)

I think this solution would leave ample space for including the preset state for [this issue](https://github.com/nervetattoo/simple-thermostat/issues/190)

**Comment by nervetattoo** [comment]
You can do both these things in 2.x by doing:

```yaml
layout:
  sensors:
    labels: false
    type: list
```
