### ISSUE TITLE
Contact sensor shows wrong state

### ISSUE THREAD

**Issue by b4dpxl** [nervetattoo/simple-thermostat#191]
This seems linked to #13. For added door/window sensors the state is showing as "on/off" instead of "open/closed". This is on the latest version installed through HACS

![image](https://user-images.githubusercontent.com/26406101/101464348-6c203780-3936-11eb-96d8-4335a5d40d8c.png)

**Comment by breti** [comment]
This issue has been reintroduced some versions ago :-(.

**Comment by mycanaletto** [comment]
Again...
