### ISSUE TITLE
[Feature Request] Option to make controls more button-like

### ISSUE THREAD

**Issue by kylehase** [nervetattoo/simple-thermostat#206]
Feature request to provide an option to make the control icons button-like to more clearly indicate they're clickable.

Here's an example I made using card-mod.

```
style: |
      ha-icon-button.thermostat-trigger {
        margin: 0 20px;
        background: var(--st-mode-background, var(--secondary-background-color));
        border-radius: 4px;
      }
```

![Screen Shot 2021-01-04 at 10 26 33 AM](https://user-images.githubusercontent.com/89047/103494987-7d4c5d80-4e7c-11eb-8a55-9946aa501756.png)

**Comment by nervetattoo** [comment]
For visual overrides there are so many unique ideas about how one wants the details, so I can only thank you for providing an example of how to achieve it using card-mod and recommend others to do it this way 👍
