### ISSUE TITLE
(feature request) Change set temp text color while waiting for the thermostat to accept the change

### ISSUE THREAD

**Issue by arigit** [nervetattoo/simple-thermostat#21]
The  Thermostat "detail" window that opens up  when clicking on the Set Temperature display on simple-thermostat has one nice feature: when changing the temperature setting in it, the new setting will change color until HA sends the command to the thermostat and confirms the change. I find this feedback information really useful.

This is a feature request to have the same behavior when change the temperature setting in the Card itself: after a change is made, change the font color (e.g. to red), wait a few seconds in case more changes are coming, and then send the command; when the setting is confirmed to be accepted by the thermostat, then return the font color ot the default value. For the choice of 'highlight' color - take in to account some ppl use dark themes so maybe make it configurable

**Comment by nervetattoo** [comment]
The card already waits before sending the command, so if you click 3 times in a row it'll only send the final command. After the command is sent you will get a small notification in HA about the service call. When calling the service we don't actually get a response if it was successful either, so there's nothing to act on by waiting. For now I won't do this as I want to keep the card as minimal as possible.
If you submit a PR i'll consider it a lot more :)

**Comment by raizyr** [comment]
One thing not mentioned here is that the display number will bounce around while this happens.   For example.  If I increase the temperature by 4 degrees, the card will increment the number each time I click.  After (or sometimes during these clicks) the card will flip back to displaying the previous temperature, then the set temperature call will be sent and the card will flip back to the temp I had tried to set.

**Comment by arigit** [comment]
@raizyr I started to notice this behaviour as well since I upgraded to HA to 0.95.4 (and python to 3.7.3), coming from 0.88, and upgrading this card to the current version of this card (the prior version I was using was from 3 months ago). I have been using this card for and I have never seen this 'bouncing' of the temperature display before. It looks like the the card is now refreshing the displayed temp value much faster than before and this causes a usability issue with the temp bouncing back even while I'm changing it which is really confusing

**Comment by arigit** [comment]
@nervetattoo just to to say thanks! - the new feature/fix works perfectly in my use-case and simple-thermostat no longer has the issue discussed here and elsewhere. It's really nice.
