### ISSUE TITLE
Honeywell thermostat: 'away' and 'home'

### ISSUE THREAD

**Issue by jbcodemonkey** [nervetattoo/simple-thermostat#212]

**Comment by jbcodemonkey** [comment]
Presently the Honeywell thermostat supports two states: Away and None.

'None' is a problematic state because different cards handle it differently.
Some assume it means there is no state or the state is unknown, which prevents the assumption the opposite of 'away' is 'home'.

Proposal:
Instead of returning 'None' as the default state, return 'Home'.

The change would be made [here](https://github.com/home-assistant/core/blob/3f948e027a9304bd7927af1c3e3b61dd25b9c292/homeassistant/components/honeywell/climate.py#L290) and [here](https://github.com/home-assistant/core/blob/3f948e027a9304bd7927af1c3e3b61dd25b9c292/homeassistant/components/honeywell/climate.py#L295).

With this change, cards like Simple Thermostat will be able to display 'Away' and 'Home' as highlighted states and toggle between them.

**Comment by nervetattoo** [comment]
This is hardly an issue with Simple Thermostat. No preset selected should be no preset selected. I'm closing this and can only assume you added an issue with HA Core if you want to follow it up.
