### ISSUE TITLE
Unit set false show false in temperature

### ISSUE THREAD

**Issue by LukaszP2** [nervetattoo/simple-thermostat#213]
![Zrzut ekranu 2021-02-24 123653](https://user-images.githubusercontent.com/44735995/108995178-00c84500-769d-11eb-8291-361a0047f164.png)

> type: 'custom:simple-thermostat'
> entity: climate.salon_szopka_termostat
> step_layout: row
> name: 'false'
> label:
>  temperature: Salon sz
> control:
>  _names: false
> unit: false

**Comment by LukaszP2** [comment]
rather not...
![image](https://user-images.githubusercontent.com/44735995/113750383-03da3a80-970b-11eb-8773-aac7ba153ce7.png)

**Comment by nervetattoo** [comment]
Clear your browser cache

**Comment by LukaszP2** [comment]
great!

one more: 
control:
    _names: false

and icon dont show ;/

![image](https://user-images.githubusercontent.com/44735995/113764966-f6797c00-971b-11eb-8546-1bf7a3fc43c4.png)
