### ISSUE TITLE
Option to hide individual setpoints

### ISSUE THREAD

**Issue by motnorge** [nervetattoo/simple-thermostat#216]
Using "hide: setpoint" you can hide the setpoint temperature(s) from showing.

For thermostats with two setpoints, it would be useful to have the option to individually hide them.

Example keywords: setpoint_low and setpoint_high

**Comment by motnorge** [comment]
>

**Comment by flyboy013** [comment]
A variation of the requested capability would be for only one set point to be displayed when the thermostat is in cool or heat modes.  When in cool mode only show the upper set point and when in heat mode only show the lower set point.  For auto, show both.  This would simplify the user interface.

**Comment by nervetattoo** [comment]
> A variation of the requested capability would be for only one set point to be displayed when the thermostat is in cool or heat modes. When in cool mode only show the upper set point and when in heat mode only show the lower set point. For auto, show both. This would simplify the user interface.

How would you prefer to configure such rules? An example would be great since I'm revamping the config format for a 2.0 release. I have some ideas, but since this is not a need I have I would much rather get input on it :)

**Comment by flyboy013** [comment]
I’m think it could be part of the “hide” option. Something like:

hide:
  inactive_setpoints: true

For a dual setpoint thermostat, if hide:inactive_setpoints is true, the lower setpoint would only show if hvac_action is heat or auto.  It would be hidden at all other times.  The upper setpoint would only show if hvac_action is cool or auto.  It would be hidden at all other times.

**Comment by flyboy013** [comment]
In version 2.0, the ability now exists to hide one of the setpoints, but this feature is "hard coded" in the the lovelace yaml file, thus the specific setpoint is permanently hidden.  My goal was for the capability to be a bit more flexible such that if the user changed the climate mode from heat to cool, the setpoint assocated with heat would get hidden and the cool setpoint would become unhidden.    As implemented I don't see how this will work.  

Is it possible to use javascript templates for the hidden true/false value?  Similar to what one can do with the [button card javascript templates](https://github.com/custom-cards/button-card#javascript-templates).

This would allow me to set true or false based on the current mode and thus the appropriate setpoint would be hidden.

**Comment by nervetattoo** [comment]
I know @flyboy013 . Create a new issue, as the original request here were hiding permanently.
I have though about supporting dynamic hide/show, but I were unable to decide on a solution in the timeframe I set myself to complete 2.0. Also, it will be a feature release, not breaking change so it can safely come as a 2.1 or something.
