### ISSUE TITLE
need to bump version in console log

### ISSUE THREAD

**Issue by Mariusthvdb** [nervetattoo/simple-thermostat#224]
<img width="611" alt="Schermafbeelding 2021-03-30 om 22 50 51" src="https://user-images.githubusercontent.com/33354141/113055074-777bc500-91aa-11eb-877c-dd384d609238.png">

nothing exciting, just nice to be correct.
thanks for updating!

**Comment by nervetattoo** [comment]
Damn robots! Thanks. Need to inspect why the semantic release pipeline is not commit back the bump into package.json (which is read in the log message)

**Comment by Mariusthvdb** [comment]
think it is still there....
```
console.info(`%c${e}: 1.0.0-development`
```

**Comment by Mariusthvdb** [comment]
and still there.... now on 2.0.1
