### ISSUE TITLE
How to disable headings on controls?

### ISSUE THREAD

**Issue by nickdos** [nervetattoo/simple-thermostat#232]
In the previous version I was using:

```yaml
control:
  _headings: false
```

To hide the "Fan mode" and "Operation" headings.

Looking at the new config, I'm not sure how to do this. 

The docs mention a `layout -> mode -> headings` object (that might do this??) but there is no information on what this `object` should contain, in terms of a data structure. 

EDIT: I tried `_names: false` under `control` but this did not hide the labels.

**Comment by nickdos** [comment]
I played around with different things and finally got it work with

```yaml
layout:
  mode:
    headings: false
```

The `object` definition threw me off.

**Comment by nibblerrick** [comment]
Thanks for writing the solution, the `object` threw me off, too.

**Comment by nervetattoo** [comment]
Thanks for replying with the solution when you found it, that is a great way to close an issue! 💯 
I've fixed the error in the documentation as you pointed out!
