### ISSUE TITLE
Compact mode

### ISSUE THREAD

**Issue by tane64** [nervetattoo/simple-thermostat#234]
After the upgrade compact mode not working.

**Comment by nervetattoo** [comment]
You need to be more specific. I have several compact cards, and they work just fine after updating the config.

**Comment by nickdos** [comment]
Change:

```yaml
layout:
  step: row
```
to
```yaml
layout:
  step: row
```

**Comment by tane64** [comment]
thank you


--
Met vriendelijke groet,
Enver Tanriverdi
