### ISSUE TITLE
'style' in card not wotking

### ISSUE THREAD

**Issue by chikehe** [nervetattoo/simple-thermostat#236]
try to change font size but nothing happens, sth i did wrong maybe?

    type: 'custom:simple-thermostat'
    style: |
      ha-card {
      --st-font-size-xl: 10px;
      --st-font-size-m: 5px;
      --st-font-size-title: 10px;
      --st-font-size-sensors: 10px;
      --st-spacing: 2px;
      }
    entity: climate.mcn02_cloud_657549
    layout:
      step: column
      mode:
        names: false
        headings: false
    control:
      hvac:
        auto: false

**Comment by nervetattoo** [comment]
Do you have card-mod installed?

**Comment by chikehe** [comment]
got it! thx!
