### ISSUE TITLE
Hide N/A for the main unit that has not temperature control

### ISSUE THREAD

**Issue by rick00001** [nervetattoo/simple-thermostat#237]
Hi,

With the new version the option to hide the temperature control is not working anymore. I used it to hide the controls for my main unit that has not temperature control, but can switch on/of all heating of my house. 

![image](https://user-images.githubusercontent.com/17128511/114151038-014f2f00-991d-11eb-9319-1d61d6b03dd3.png)

Still really liking the card by the way! (Y)

**Comment by nervetattoo** [comment]
You can disable all setpoints with:

```yaml
setpoints: false
```

**Comment by rick00001** [comment]
Thanks for your reply, i had it under hide: moved it to the root tree and
it works! Thank you!

Op vr 9 apr. 2021 om 23:02 schreef Raymond Julin ***@***.***>:
