### ISSUE TITLE
Repostitory structure for v2.2.2 is not compliant

### ISSUE THREAD

**Issue by micblazek** [nervetattoo/simple-thermostat#242]
At the moment I cannot install it via HACS.

![Image 009](https://user-images.githubusercontent.com/3628907/114286074-f8b14280-9a5b-11eb-8e50-d8996fa93c25.png)

**Comment by Flash3dee** [comment]
After removing through the "Uninstall" option in Hacs I'm still getting this error in my HA Core log:
2021-04-11 13:13:42 ERROR (MainThread) [custom_components.hacs] nervetattoo/simple-thermostat - Repostitory structure for v2.2.2 is not compliant

How to get rid of that (cosmetic?) error?

**Comment by sym0nd0** [comment]
I've just done a full clean install and following installing HACS, I'm receiving this error in my HA logs.

I'm guessing that once @nervetattoo has updated the integration to be compliant (manifest maybe?) that it will go away and those that want to install it will once again be able to.

**Comment by sym0nd0** [comment]
Error persists in v2.3.0, I'll open a fresh issue in a sec.

**Comment by nervetattoo** [comment]
Its rather unclear from the validation what fails.
I'm guessing perhaps it is that I now release 2 files in the GH release (regular + a debug release) that somehow messes things up. Will try to remove the debug in the next build
