### ISSUE TITLE
Temperature display does not change

### ISSUE THREAD

**Issue by DeeJaWue** [nervetattoo/simple-thermostat#245]
Hello, 

Since Version 2.0 I have the issue, that when change the temperatur for example from 20.0 to 22.0 the display changed only from the black 20.0 to red 20.5, after that there are no changes.

After some seconds (about 20 sec) the display changed to 22.0 degree, when I have pressed the plus button often enough.

Before changing the temperature:

![Screenshot_20210411_120623_io homeassistant companion android_edit_1192495248050851](https://user-images.githubusercontent.com/10549877/114300151-15329680-9abf-11eb-9852-a400408dbf9f.jpg)

After pressing plus button 5 times:
![Screenshot_20210411_120629_io homeassistant companion android_edit_1192505623392516](https://user-images.githubusercontent.com/10549877/114300184-4b701600-9abf-11eb-8562-8117153c4290.jpg)

After 15 seconds:
![Screenshot_20210411_120653_io homeassistant companion android_edit_1192518199260743](https://user-images.githubusercontent.com/10549877/114300200-5cb92280-9abf-11eb-8850-7170f26921e2.jpg)

That's my simple config:
![Screenshot_20210411_121748_com android chrome_edit_1193140897962211](https://user-images.githubusercontent.com/10549877/114300363-4364a600-9ac0-11eb-8be5-986a1ab5cf81.jpg)

**Comment by aneisch** [comment]
I have the same issue I think. I can change the temperature once (step size 1 for me) but changes of more than one don't reflect on the interface.

**Comment by StWiesi** [comment]
I have the same issue. The first change of temperature is reflected right away, but the next ones need time until they are really displayed. There seems to be a delay after the first change.

**Comment by PronkMedia** [comment]
I'm encountering the same issue after updating to v2. I personally think this should be labeled as 'bug' in stead of 'enhancement'. 

Especially when using a lower step_size (e.g. 0.1) it's very hard to adjust it with e.g. 0.8 as I lose track of how many times I clicked and visually I get no feedback until it's set/debounced.

**Comment by mikesplain** [comment]
Agreed, I'm running into this as well. I've been attempting to debug but haven't come up with anything meaningful.

**Comment by DeeJaWue** [comment]
Thank you so much, it works!😊

**Comment by mikesplain** [comment]
Fixed for me too, thanks!

**Comment by PronkMedia** [comment]
Just tested it, works great again. Thank you!
