### ISSUE TITLE
Repostitory structure for v2.3.0 is not compliant

### ISSUE THREAD

**Issue by sym0nd0** [nervetattoo/simple-thermostat#246]
I don't have this card or repo installed, my current HA install is fresh as of this morning but I did have it installed on a previous HA setup.

```
Logger: custom_components.hacs
Source: custom_components/hacs/operational/factory.py:58
Integration: HACS (documentation, issues)
First occurred: 21:24:25 (1 occurrences)
Last logged: 21:24:25

nervetattoo/simple-thermostat - Repostitory structure for v2.3.0 is not compliant
```
Having now tried to install this, so that I can test if uninstalling it stops the error from occurring in my logs, when I try to add the custom repo

`https://github.com/nervetattoo/simple-thermostat`

I'm unable to, receiving the error

> Repostitory structure for v2.3.0 is not compliant

**Comment by kimvognsen** [comment]
I have same error

**Comment by nervetattoo** [comment]
Tried removing and reinstalling 2.3.1 now. Did not see any errors so will close and hope it works for everyone.

**Comment by sym0nd0** [comment]
Nope. Same with v2.3.1.

**Comment by sym0nd0** [comment]
And now 2.3.1 is working fine. No errors in logs and I'm unable to install etc. Huzzah!

Thanks
