### ISSUE TITLE
HACS install setting resources to /null

### ISSUE THREAD

**Issue by cjsmns** [nervetattoo/simple-thermostat#247]
I'm having an issue with this plugin installing via HACS. When installed it all seems good, but adding a card shows the dreaded red box error saying the custom card is not installed.

Turns out that the resource url that HACS sets is `/hacsfiles/simple-thermostat/null`. Changing this to the url on the one on github in the install instructions fixes this, but then HACS compains that the card is now **Not loaded**.

I've only just started using this card as of yesterday and had this problem. Thought it might have just been a once off so manually fixed it, but todays update broke it again setting the url to /`null` again. I don't have any errors showing up so I'm not sure what is going on.

**Comment by nervetattoo** [comment]
Did this get fixed by https://github.com/nervetattoo/simple-thermostat/releases/tag/v2.3.1 for you?

**Comment by cjsmns** [comment]
👍 Yes, looks like it. Just done the update and everything seems to be working like it should.
