### ISSUE TITLE
Add OFF state if minimum temperature is reached

### ISSUE THREAD

**Issue by l154** [nervetattoo/simple-thermostat#25]
hi,
is there any possibility to add OFF state rather than minimum temperature ?? like on an image ?
![image](https://user-images.githubusercontent.com/4931151/52650358-639d7800-2eea-11e9-9a7d-5a6243347c80.png)

br L154

**Comment by nervetattoo** [comment]
I'm not sure I understand what you are asking for.
Do you want it to display `OFF` when it is set to min_temp? Or do you want to hide the temperature setting when mode is `Off`?

**Comment by nervetattoo** [comment]
Closing for lack of further input
