### ISSUE TITLE
Unable to hide label 'Preset'

### ISSUE THREAD

**Issue by NielsDWG** [nervetattoo/simple-thermostat#251]
Since the new update I cannot hide the label in front of the predefined modes (see image). I am able to change the text using the _name property, but I want do not want to show the label at all.

My yaml:
type: 'custom:simple-thermostat'
entity: climate.toon_thermostat
header:
  name: Verwarming
  icon: 'mdi:radiator'
label:
  temperature: Temperatuur
  state: Status
control:
  _headings: false
  preset:
    _name: 'Preset'
    _hide_when_off: true
    eco: false
    home:
      name: ''
      icon: 'mdi:home'
    away:
      name: ''
      icon: 'mdi:logout-variant'
    comfort:
      name: ''
      icon: 'mdi:sofa'
    sleep:
      name: ''
      icon: 'mdi:sleep'

![image](https://user-images.githubusercontent.com/50589052/115121459-27c33900-9fb3-11eb-8f9c-5ce9f97398aa.png)

**Comment by nervetattoo** [comment]
As per the documentation you should read after updating to 2.x:
```yaml
layout:
  mode:
    headings: false
```

**Comment by NielsDWG** [comment]
Thank you. I completely missed that!
