### ISSUE TITLE
How to hide current climate state in card?

### ISSUE THREAD

**Issue by tmchow** [nervetattoo/simple-thermostat#253]
**Is your feature request related to a problem? Please describe.**
Want to be able to hide the climate state (e.g `Heat`) since it's redundant information in some configurations of the card.
See this example where I'm showing the icons of the current state so adding the label as well is redundant.

![image](https://user-images.githubusercontent.com/517103/115766706-1f755000-a35d-11eb-917f-c4fc97e9a20f.png)

**Comment by nervetattoo** [comment]
Did you read through the docs for [sensors in the beta release](https://github.com/nervetattoo/simple-thermostat/blob/beta/examples/sensors.md)?

**Comment by tmchow** [comment]
@nervetattoo No I didn't but didn't think it applied to this exactly as that seems like a sledgehammer to solve this issue. Maybe i'm wrong?

**Comment by tmchow** [comment]
@nervetattoo I just checked it out, thanks.  I started to muck with it after upgrading to 2.4 beta 2.  However, I'm not getting any changes that I'd expect so think I am interpreting it incorrectly.

With this, I thought I'd get `test` in place of `heat` string

![image](https://user-images.githubusercontent.com/517103/115785583-818d7f80-a374-11eb-864e-c37c431482a8.png)

**Comment by nervetattoo** [comment]
Oh, wait, if you actually had the beta version running you would just see `Heat`, and it would read `Operation` not `State` for the label. So this just means you are effectively not running the beta card.
That is most likely down to browser cache of the old version of the card.

To get it to read just `Heating` you can use a config like this:

```yaml
id: state
label: "{{ui.operation}}"
template: "{{hvac_action|translate('state_attributes.climate.hvac_action.')}}"
```

In the final 2.4 version I hope to make that translation expression far easier, but for now that will work.

**Comment by nightfever77** [comment]
I am on v2.4.0-beta.2 and your code does not seeam to work
[image](https://user-images.githubusercontent.com/73058571/115876296-6a1ec700-a446-11eb-85b1-4a3c42449bb5.png)

**Comment by tmchow** [comment]
@nervetattoo @nightfever77 it was indeed a browser cache issue. Flushed the cache and it now works.

![image](https://user-images.githubusercontent.com/517103/115893824-7aff1680-a40d-11eb-93b3-176ddd0cbae6.png)
