### ISSUE TITLE
Old button graphics in hass 0.88

### ISSUE THREAD

**Issue by Edoardo396** [nervetattoo/simple-thermostat#29]
Hey man, thanks for your wonderful work. 
Is it still possible to have the old buttons graphics in hass 0.88+?
I liked it more than these new blue-ish buttons.

This is the new graphics it it showing to me:
![image](https://user-images.githubusercontent.com/13950625/53417968-feac4c80-39d6-11e9-90eb-b9dab44c7a73.png)

Thanks

**Comment by nervetattoo** [comment]
No, that will not happen given that 0.88 replaced and moved forward with a new set of buttons and I intend to keep aligned with that direction. I might tweak active state on the new buttons, but overall this is the visual direction it'll be on. Sorry that doesn't fulfil your request.

**Comment by Edoardo396** [comment]
No problem, thanks anyway
