### ISSUE TITLE
How works the name of a specific mode under the modes?

### ISSUE THREAD

**Issue by gigios** [nervetattoo/simple-thermostat#32]
I have updated today to the version 0.19 and all works fine.
No I want change the list of modes available in the card, and with the new modes key I'm able to do all these changes.
My question is related the key 'name', if I use a different name in my config, seems that it's ignored. I can see always the original mode name!

```        modes:
          "Timer":
            include: false
            icon: mdi:av-timer
          "Tado mode":
            include: false
          "Manual":
            name: Make it cold
            icon: mdi:cursor-pointer
          "Smart schedule":
            name: Test description
            icon: mdi:calendar-clock
          "Off":
            name: Make it cold
            icon: mdi:power
          "On":
            name: Warmer!
            icon: mdi:fire
```

There is also a way to remove completely the name and use only the icon?

**Comment by nervetattoo** [comment]
Funny thing; I planned to, and even did, implement this, but at the last moment i ripped it out again. I had some reason but now I can't imagine what that reason might have been. I will add it back, with support for setting both name and icon to `false` to hide either one of them. That should offer full flexibility.
