### ISSUE TITLE
st-mode-active-color not working

### ISSUE THREAD

**Issue by tenkaibr** [nervetattoo/simple-thermostat#322]
As the title says, "st-mode-active-color" is not working.

It seems that a specific css was used for each type of mode because each one has a different color. Would it be possible to dismember?

**Comment by mattdevo1** [comment]
> As the title says, "st-mode-active-color" is not working.
> 
> It seems that a specific css was used for each type of mode because each one has a different color. Would it be possible to dismember?

--st-mode-active-color (which is the text color for active mode buttons) is working fine for me in v2.4.3.

But --st-mode-active-background doesn't seem to be working for me (which is supposed to change the background color of the active mode button). Each mode button has a different color when active right now, I am trying to change them so they are always green when active.

Would love to see this changed/fixed, thanks!

**Comment by mattdevo1** [comment]
This should have been fixed in 2.5.0. Take a look and see if it works for you now.
