### ISSUE TITLE
Support for different regulations modes

### ISSUE THREAD

**Issue by fredriklj** [nervetattoo/simple-thermostat#33]
It is not too uncommon for a HVAC system to set the operation_mode automatically based on the target temperature, and offer the user the option to set fan_mode instead. In such cases, the HVAC system may regulate the room temperature by selecting cooling, heating, idling et cetera without user intervention, whereas operation_mode is a read-only variable.

It would have been nice if it was possible to configure simple-thermostat to take the fan_mode/fan_list as input for the control icons instead of operation_mode/operation_list.

The operation_mode icon could however still be rendered alongside the card name, but should also be configurable to support modes such as heat/cool regeneration, et cetera. Related to this, I would also recommend to clarify the difference between mode and state in the documentation.

**Comment by fredriklj** [comment]
And, as a side note, this hack is what I currently have to get this working for me. I also noted (related to #34) that there is no localization for 'Temperature' within the climate section, so I am getting it from elsewhere.

However, it should be selectable wether you want to control operation_mode and fan_mode.

    diff --git a/index.js b/index.js
    index cc8e567..bc5549d 100644
    --- a/index.js
    +++ b/index.js
    @@ -98,8 +98,8 @@ class SimpleThermostat extends LitElement {
     
           const {
             attributes: {
    -          operation_mode: mode,
    -          operation_list: modes = [],
    +          fan_mode: mode,
    +          fan_list: modes = [],
               ...attributes
             },
           } = entity
    @@ -219,7 +219,7 @@ class SimpleThermostat extends LitElement {
             min_temp: minTemp = null,
             max_temp: maxTemp = null,
             current_temperature: current,
    -        operation_mode: activeMode,
    +        fan_mode: activeMode,
             ...attributes
           },
         } = entity
    @@ -228,10 +228,10 @@ class SimpleThermostat extends LitElement {
         const sensorHtml = [
           _hide.temperature
             ? null
    -        : this.renderInfoItem(`${formatNumber(current)}${unit}`, 'Temperature'),
    +        : this.renderInfoItem(`${formatNumber(current)}${unit}`, this.localize('ui.card.weather.attributes.temperature')),
           _hide.state
             ? null
    -        : this.renderInfoItem(this.localize(state, 'state.climate.'), 'State'),
    +       : this.renderInfoItem(this.localize(state, 'state.climate.'), this.localize('ui.card.climate.operation')),
           _hide.away ? null : this.renderAwayToggle(attributes.away_mode),
           sensors.map(({ name, state }) => {
             return state && this.renderInfoItem(state, name)
    @@ -436,9 +436,9 @@ class SimpleThermostat extends LitElement {
     
       setMode(mode) {
         if (mode && mode !== this._mode) {
    -      this._hass.callService('climate', 'set_operation_mode', {
    +      this._hass.callService('climate', 'set_fan_mode', {
             entity_id: this.config.entity,
    -        operation_mode: mode,
    +        fan_mode: mode,
           })
         }
       }

**Comment by nervetattoo** [comment]
Makes sense. From your experience, can this safely be detected based on the passed data? What would be good criteria for falling over to fan_mode? Should just its mere existence be sufficient?

**Comment by fredriklj** [comment]
I guess the safest way is to have it configurable, such that is "autooperation" is true, fan_mode control input instead. I'm sure there are systems which takes both inputs, but this way there will at least be an option of one or the other.

**Comment by fredriklj** [comment]
Any chance you've had the time to figure out the best way to do this? :)

**Comment by nervetattoo** [comment]
Haven't had time to prioritise it, but its not forgotten :)
