### ISSUE TITLE
Localization seems not to work properly

### ISSUE THREAD

**Issue by fredriklj** [nervetattoo/simple-thermostat#34]
As shown on the screenshot on the project page (thermostat-card.png), localization seems to not work properly for "Temperature" and "State". Neither have I been able to have localization of the state itself.

Also, given that the translations provided through hass is not always very accurate in this area (depending on context), and all possible states may not have translations at all, it would also have been nice to have the option to override these in the card configuration.

**Comment by nervetattoo** [comment]
Hmm. I do think the concept of overriding translations in custom cards is interesting. If I add this it will be not the most user friendly as its so hard to know what parts of the translation object the card will use with custom sensors. But supporting overriding specific keys in the HA provided localisation resources by the exact same keys could be a neat convention for custom cards in general:

```yaml
translations:
  en:
    state.climate.on: Its on
```

It would require you as the user to gather somewhat deeper knowledge of internal data structures in HA, but then again it would allow you to pinpoint any translation field in any language just for this one card. Should be future proof. Will ponder it further 🤔

**Comment by Misiu** [comment]
@nervetattoo I also stuck a bit on localizing. I always got `Temperature`. My quick fix was editing JS file with the correct string.
This would be a great addition :)

**Comment by Misiu** [comment]
@nervetattoo I've just updated HA to the latest version and there is something wrong with localization:
![image](https://user-images.githubusercontent.com/1741838/66347791-6b1c0080-e955-11e9-8d83-205a5a8d8c42.png)

Take a look at Status (State). On the label it is written `heating` but the button says: `GRZANIE`, which means heating in Polish. So the buttons are correctly localized, but the label isn't.

**Comment by nervetattoo** [comment]
Thanks to [this PR](https://github.com/nervetattoo/simple-thermostat/pull/82) this is at least now possible to override so I'm leaving it at that solution

**Comment by Protoncek** [comment]
Hi! 
I know this is an old thing, but, is it possible that this error reappeared? 
on image below buttons are translated, while current status is in english:
![image](https://github.com/nervetattoo/simple-thermostat/assets/26406640/4e7413d5-50a6-4ffe-b7fe-a3d44ce125bd)
