### ISSUE TITLE
The fan and swing control didn't display anything

### ISSUE THREAD

**Issue by dsus4wang** [nervetattoo/simple-thermostat#344]
![image](https://user-images.githubusercontent.com/58458517/175056512-1eee7eca-db3c-4cd5-ad4d-178682abe980.png)
I am configuring my air conditioning control, but the plug-in does not display the icon or text of wind speed and swing. Even if I customize them, they still do not work
What should I do? thanks!

**Comment by aquarius15283** [comment]
The option "show mode names" should be activated because icons for some modes of fan/swing are not available.

**Comment by tolrahC** [comment]
any update or workaround for this issue?  Thank you

**Comment by dsus4wang** [comment]
> any update or workaround for this issue? Thank you
add icon label
eg:
icon: mdi:wifi-strength-3
