### ISSUE TITLE
Incorrect handling of Ecobee target temps

### ISSUE THREAD

**Issue by jjlawren** [nervetattoo/simple-thermostat#35]
Since the 0.20 upgrade, my Ecobee thermostats show two "null.0" temperature selectors when in standard `heat` or `cool` operation modes. I believe the card is looking for the `target_temp_high` and `target_temp_low` attributes when these are not used in these modes. It should just be using the single target named `temperature`.

Entity attribute dump:
```
==================================================
                 climate.upstairs
--------------------------------------------------
                    State: heat
         ---------- Attributes ----------
            actual_humidity: 33
                   aux_heat: off
                  away_mode: off
               climate_list: ['Away', 'Sleep', 'Home']
               climate_mode: Home
        current_temperature: 69
                        fan: off
                   fan_list: ['auto', 'on']
            fan_min_on_time: 0
                   fan_mode: auto
              friendly_name: Upstairs
                  hold_mode: None
                   max_temp: 95
                   min_temp: 45
                  operation: idle
             operation_list: ['auto', 'auxHeatOnly', 'cool', 'heat', 'off']
             operation_mode: heat
         supported_features: 3575
           target_temp_high: None
            target_temp_low: None
                temperature: 67
```

**Comment by anthonym21** [comment]
Same issue with Nest

**Comment by ptdalen** [comment]
I have two ecobee 3 thermostats and also have this same behavior.  Setting to Auto does work, but heat only or AC only shows two temp adjustment areas both set to null

**Comment by nervetattoo** [comment]
This should be improved in 0.21. Given I don't have a Ecobee I can't verify it actually works in real life, so please confirm or re-open if it doesn't help.

**Comment by jjlawren** [comment]
Works!

**Comment by nervetattoo** [comment]
That was fast feedback @jjlawren ! 💃
