### ISSUE TITLE
Allow "more-info" pop-up on optional sensors

### ISSUE THREAD

**Issue by aheath70** [nervetattoo/simple-thermostat#37]
If you specify additional sensors to display such as humidity, or even the default temperature sensor which is displayed does not allow you to click on them to display "more-info".

**Comment by nervetattoo** [comment]
Uhm, actually, extra sensors do very much support this. You can click on the value to open the more-info.
For the thermostat entity itself you can click on the name/icon of the card if you are on 0.20, or the target temperature value itself if you are on earlier.

Doesn't this work for you? If so can you try to do it with the browsers developer tools console open and report any errors in it as well as your browser/version/os combo?

**Comment by aheath70** [comment]
Indeed, you are correct - my mistake!

I do note though that the default temperature sensor is not clickable. I had to hide the default one using:

```
hide:
  temperature: true
```

... and then add another temperature sensor using 

```
sensors:
  - entity: sensor.sn3_temperature
    name: Temperature
 ```

**Comment by nervetattoo** [comment]
The temperature attribute is a bit harder to get clickable as the entity id for a potentially underlying sensor entity is not exposed. I have the same issue with some generic thermostats myself. Will close as the main question is answered.
