### ISSUE TITLE
null.0°C

### ISSUE THREAD

**Issue by septeven** [nervetattoo/simple-thermostat#38]
Hi,
Since a few days (I would say since 0.20 but can't be certain of that), my thermostat card is showing null.0°C, which makes setting the temperature impossible.

Is there any breaking change that we should be aware of  ? I'm using it with a Nest Thermostat.

Thanks

**Comment by jjlawren** [comment]
Looks similar to https://github.com/nervetattoo/simple-thermostat/issues/35. Affects both Nest and Ecobee.

**Comment by septeven** [comment]
Yes sounds like it is

**Comment by nervetattoo** [comment]
This should be improved in 0.21. Given I don't have a Nest I can't verify it actually works in real life, so please confirm or re-open if it doesn't help.

**Comment by septeven** [comment]
yes that fixed it ! thanks
