### ISSUE TITLE
Settings with a temperature range results in "null" for current temp setting

### ISSUE THREAD

**Issue by jsblake** [nervetattoo/simple-thermostat#4]
Some thermostats (like the Nest) allow you to set a range of temperatures (IE: turn on the heat if it drops below 60F, turn on the a/c if it rises above 80F). When a Nest is in this mode, simple-thermostat shows "null" as the temperature setting. 

Example: 
Screenshot of my thermostat setting from the old legacy UI: 
![image](https://user-images.githubusercontent.com/82084/49416648-b91a1380-f748-11e8-883e-be9442ea4c24.png)

Screenshot of simple-thermostat at the exact same setting: 
![image](https://user-images.githubusercontent.com/82084/49416623-9c7ddb80-f748-11e8-81fe-c17c01bb52a9.png)

**Comment by nervetattoo** [comment]
Oh, I didn't know this was a thing. Thanks. I will look into it but will probably need some more information unless I find a way to debug this with some kind of virtual nest thermostat myself.

**Comment by mahoek** [comment]
I think this is happening when the Nest goes to Eco

**Comment by jsblake** [comment]
Yes, eco mode is usually when you have this on a nest. 

For what it's worth, non-Nest thermostats can have a similar setting as well. Many Z-Wave thermostats can be in an "auto" mode where they have a min/max temperature and flip back and forth

**Comment by robertotucci** [comment]
I have the same issue...there are some news about it?

**Comment by nervetattoo** [comment]
I finally spent some time setting up a pure development HA install with mock components so I could look into this issue. My main focus is to _get it functional_, not making it brilliant. Will this UI suffice?

<img width="506" alt="Screenshot 2019-03-09 at 23 29 30" src="https://user-images.githubusercontent.com/45449/54078150-82154a00-42c3-11e9-88ab-1d13b7e0335c.png">

Only have the ecobee example to go by so I don't know if the passed data that I can act on differs. I'm relying on `target_temp_min` and `target_temp_low` being attributes and if so the card renders one control for each of those. If you know that your device does not work this way please tell me how it works so I can cater for it.

**Comment by nervetattoo** [comment]
Shipped in 0.20
