### ISSUE TITLE
custom-cards org

### ISSUE THREAD

**Issue by iantrich** [nervetattoo/simple-thermostat#40]
Invitation to bring your repo over to the community custom-cards organization: https://github.com/custom-cards/information

Let me know if you're interested and I can float you an invitation to the org. Thanks!

**Comment by iantrich** [comment]
Hey @nervetattoo , any thought on this? Thanks.

**Comment by nervetattoo** [comment]
Sorry for not replying to this @iantrich . I've really not had any time to work on the card for a long time until now. At the moment I don't want to move the card as I think the notion of a custom-cards org is an anti pattern and I prefer to keep the repo under my account as long as I'm a sole developer. If at any point other contributors makes it more into a team effort I'll reconsider :)

**Comment by iantrich** [comment]
So if I contribute you'd consider 😂?

**Comment by iantrich** [comment]
A possible compelling reason to move: https://custom-components.github.io/hacs/
Supports cards in the custom-cards org by default making it really easy for people to find new things
