### ISSUE TITLE
Temperature setting is too fast

### ISSUE THREAD

**Issue by fredrike** [nervetattoo/simple-thermostat#44]
The Daikin climate component is async in 0.91 and it seems like the simple-thermostat is too quick with updating the the temperature state. When I click temp down it immediately goes up to the previous value.

If I set the temperature in the standard lovelace climate card (or in the entity detail card) it works as expected (and before).

Related to #41

**Comment by flyboy013** [comment]
@fredrike have you found a workaround for this issue? Issue #41 has been around for 25 days with no resolution yet.

**Comment by nervetattoo** [comment]
I did some changes to the set temperature logic in 0.22, does that improve things for you @fredrike ?

**Comment by nervetattoo** [comment]
I will close this issue and if there are any new info regarding changing temperature add it to #41 which I'll keep open until fully resolved
