### ISSUE TITLE
Custom element doesn't exist with HA 0.91.2

### ISSUE THREAD

**Issue by kpj5425** [nervetattoo/simple-thermostat#47]
I'm getting the error that the custom element doesn't exist. Finally got it to work last night and then new update to HA and Custom components changed and I lost my card. Love this card over the stock thermostat card. Please someone help me figure this out.

**Comment by aheath70** [comment]
I'm running 0.91.2 and it is working flawlessly for me. I am using the custom_updater method to install.

**Comment by kpj5425** [comment]
can you give me a good run down of how to install that cuz most installs on github assume you know everything and I'm just trying to learn but it's hard to learn when its missing critical details. I also can't get the tracker card to work either.

**Comment by kpj5425** [comment]
after much moving of files and whatnot, I got my simple thermostat card and tracker card working now.

**Comment by aheath70** [comment]
@kpj5425 - Glad you worked it out. I just followed the guides on setting up the tracker card on the Github page. I know what you mean. I am an IT guy, but on the infrastructure side, so Github is a bit of a mystery to me as well.

**Comment by talondnb** [comment]
This card works fine for my admin user but for some reason it won't load for my wife's phone who's a regular user. I did try to login with my user on her phone but still wouldn't show up. Any ideas?

**Comment by nervetattoo** [comment]
> This card works fine for my admin user but for some reason it won't load for my wife's phone who's a regular user. I did try to login with my user on her phone but still wouldn't show up. Any ideas?

Might be a browser issue. What phone/browser/os version is it?

**Comment by nervetattoo** [comment]
Closing this in lack of feedback
