### ISSUE TITLE
Show "friendly name" for mode

### ISSUE THREAD

**Issue by fredrike** [nervetattoo/simple-thermostat#5]
It would be great if `state` and `mode` would show the nicer formatting i.e. `fan_only` is shown as `Fan only` as for the traditional climate entity.

**Comment by fredrike** [comment]
It seems that it should be localized..

https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/components/ha-climate-state.js#L109

**Comment by nervetattoo** [comment]
That should fix it, thanks for reporting it, didn't think this far :)
