### ISSUE TITLE
Add support for dual thermostats

### ISSUE THREAD

**Issue by pbeckcom** [nervetattoo/simple-thermostat#55]
This is a beautiful card, please add support for thermostats that reports a separate entity for heat and cool.  Maybe just add a separate temperature setpoint up/down set for the 2nd climate entity.

![image](https://user-images.githubusercontent.com/46651681/58963279-7de9b300-8772-11e9-9f81-5d674faef53f.png)

**Comment by nervetattoo** [comment]
How does this even work in reality? Do operation_mode/fan_mode mirror across the two entities? What about temperature? (I see they are the same)
I mean, if you set one of the to `on` and not `auto` will the other one go to `off`?
I find the concept of two entities for one controllable device very confusing :)

**Comment by kethoth** [comment]
It has separate entities for Heat and Cool set points, that's the only real difference.  [There's already a custom card that supports this](https://github.com/enriqg9/dual-thermostat), but it's not the same style as yours.

**Comment by nervetattoo** [comment]
I have an air conditioner control unit that generates 4 entities, which makes me wonder where the limit goes and how on earth its practical to support (to me) weird devices like this. For me the card currently works as I want so I can't see me getting to this very soon, but I would love to see input on how to practically do this. Like, sketches and proposed configs that would result in those sketches, would be great. And also to get feedback from more users hopefully.

**Comment by kethoth** [comment]
Travelling this week so pardon the poor edit but see the (hopefully)
attached image for what I was thinking

**Comment by kethoth** [comment]
Something like this with options for both setpoints, maybe only if both heat and cool setpoint entities are in the card config.

![image](https://user-images.githubusercontent.com/46651681/59377731-76994b00-8d18-11e9-95f3-5405231684e6.png)

**Comment by UbhiTS** [comment]
I would really love and appreciate this above change that @kethoth has recommended. I use CT101 thermostats and the dual thermostat card works well. Only it's not as pleasing to the eyes as yours. if you could have the entity as entity_cool, entity_heat and depending on the heat / cool mode call the correct entity, that would be awesome. BTW, love your UI, so simple and elegant.

**Comment by mar005** [comment]
I would agree with this. I may try to edit the dual thermostat card that was pointed out by @kethoth with css but still unfamiliar with modding a card, so I have been looking for a smaller card that fits on my mobile HA iOS nicely to edit my 2 thermostats. I have 2 Trane Z Wave thermostats that created multiple entities per thermostat (4 climate entities per thermostat, ridiculous!), but they work well I only have to use a 1 heat and 1 cool out of the 4 and yes they mirror the humidity, temperature and other sensor data inside it. 

I also wanted to use this other card [nest looking thermostat card](https://github.com/ciotlosm/custom-lovelace/tree/master/thermostat-card), but also doesn't support dual thermostats [yet](https://github.com/ciotlosm/custom-lovelace/issues/211)

**Comment by nervetattoo** [comment]
I'm closing this as it seems like [dual entity thermostats are not supposed to be](https://github.com/home-assistant/home-assistant/pull/27040)
