### ISSUE TITLE
Fan speed

### ISSUE THREAD

**Issue by adrianmihalko** [nervetattoo/simple-thermostat#56]
I am using [SmartIR](https://github.com/smartHomeHub/SmartIR) component to control my AC unit:

<img width="373" alt="Screenshot 2019-06-10 at 23 55 17" src="https://user-images.githubusercontent.com/733361/59229701-6e87c100-8bdb-11e9-8891-bd36d0d8024f.png">

Is there any way to set fan speed like in original climate component?

Simple thermostat in GUI:

<img width="501" alt="Screenshot 2019-06-10 at 23 58 14" src="https://user-images.githubusercontent.com/733361/59229782-a2fb7d00-8bdb-11e9-9a3c-ab9b408db4c3.png">

**Comment by nervetattoo** [comment]
You can toggle the `mode_type` to instead of having operation mode you get fan mode. But you can't have them both, so if you want to change both you're currently out of luck.
If you only want to control fan mode then just do:
```yaml
mode_type: fan
```

**Comment by nervetattoo** [comment]
In 0.26 this should be better supported
