### ISSUE TITLE
Some CSS not working (for ACTIVE mode)

### ISSUE THREAD

**Issue by TheStigh** [nervetattoo/simple-thermostat#58]
Hi,

Seems '--st-mode-active-background' and '--st-mode-active-color' doesn't work? Can anybody confirm this? Quite annoying that I can't change the color of text and frame around the active mode chosen.

EDIT:
I found this code in your .js file:
```
            <mwc-button
              ?disabled=${e===t}
              ?outlined=${e===t}
              ?dense=${!0}
              @click=${()=>this.setMode(e)}
            >
              ${i(n.icon)} ${s(e,n)}
            </mwc-button>
```
Did you intent to make the non-selected modes 'disabled' and the active mode with colors?
If I go through chrome dev and remove 'disabled', the color (according to styling) is back.

**Comment by fredrike** [comment]
I've tried to identify the CSS name of the active but without success..

**Comment by WildeRNS** [comment]
also found that not working. i used that code:
`style: |
  div.mode-item.active {
    background: var(--paper-toggle-button-checked-button-color)
  }
  div.mode-item {
    background: var(--paper-toggle-button-unchecked-button-color)
  }`

**Comment by mckochan** [comment]
'--st-mode-active-background' and '--st-mode-active-color' still aren't working for me. Anyone have a working config?
