### ISSUE TITLE
current_temperature: null

### ISSUE THREAD

**Issue by CarpeDiemRo** [nervetattoo/simple-thermostat#61]
Hello, I'm using Broadlink to control an old Samsung AC and current temperature appears current_temperature: null. It seems to be normal as far as my AC doesn't send temperature data back to HA. My questions are:

1. There is any possibility to integrate Broadlink A1 sensor in order to populate current_temperature: field?
2. If not, there is any possibility to remove/hide current_temperature: field? Because it's pretty useless to display no info there.

![2019-07-18_14h08_45](https://user-images.githubusercontent.com/38489167/61453136-0b214980-a966-11e9-94e1-ae8a62f6ddef.png)
![2019-07-18_14h11_15](https://user-images.githubusercontent.com/38489167/61453137-0bb9e000-a966-11e9-9ef0-3684d2d5a140.png)

**Comment by nervetattoo** [comment]
I guess the best you can do is to hide the temperature and use a sensor listing as you already do:
```yaml
hide:
  temperature: true
```

I'm happy to review any PR for this but I don't have time to implement it myself.
