### ISSUE TITLE
Problems after upgrade to HA 0.96.0

### ISSUE THREAD

**Issue by matisaul** [nervetattoo/simple-thermostat#62]
Hi @nervetattoo !
First of all, thanks for this great card!
I updated to 0.96.0, and there was some changes in climate domain... Now I don't get the 'heat' and 'off' buttons... Could you take a look on this? Thanks in advance!!

**Comment by TEO984** [comment]
Idem here!!
thanks for this card!!

**Comment by rummystrong** [comment]
I have the same issue. Thank you!

**Comment by talondnb** [comment]
Same here.

**Comment by SteveDinn** [comment]
Came here to log this bug.

**Comment by zanix** [comment]
Apparently the climate domain was overhauled in 0.96.0
https://www.home-assistant.io/blog/2019/07/17/release-96/#climate

**Comment by nervetattoo** [comment]
I'm aware of these changes in 0.96 but I'm on vacation and probably won't be able to look into this until I'm well home and am ready to upgrade HA myself.

**Comment by mokshmridul** [comment]
@nervetattoo Thank you so much mate. Have a great vacation :)

**Comment by matisaul** [comment]
Don't worry, enjoy your holidays!

**Comment by akmolina28** [comment]
I submitted a pull request to fix this problem. I got it working again for my ecobee thermostat. Thanks @nervetattoo for the awesome code!

![thermostat](https://user-images.githubusercontent.com/2997206/61990892-7cb86200-b00e-11e9-95c0-3716cdecb8b9.png)

**Comment by TurboTronix** [comment]
> I submitted a pull request to fix this problem. I got it working again for my ecobee thermostat. Thanks @nervetattoo for the awesome code!
> 
> ![thermostat](https://user-images.githubusercontent.com/2997206/61990892-7cb86200-b00e-11e9-95c0-3716cdecb8b9.png)

Care to share your code? My Ecobee is still not showing the icons...

**Comment by rummystrong** [comment]
@akmolina28 What changes did you make to get it working again? Thanks

**Comment by nervetattoo** [comment]
Everyone, please upgrade and test the [0.26 pre-release](https://github.com/nervetattoo/simple-thermostat/releases/tag/0.26.0-0) and see what works/doesn't with 0.96 for you.
I know it lacks some things like matching icons to state (action) but it should solve the basic features. Thanks @akmolina28

**Comment by devotio** [comment]
I tried upgrade, but did not see any change.
I copied the new simple-thermostat.js file to the www/ folder and restarted HA.
Did I miss something?

**Comment by mokshmridul** [comment]
I updated and restarted too, but it did not work.

**Comment by akmolina28** [comment]
Probably your browser caching the old version of the script. Make sure you force a cache bust by changing the version number in the query string. You can change it to whatever you want as long as it is different.

```
  - url: /local/simple-thermostat.js?v=0.26.0
    type: module
```

**Comment by devotio** [comment]
Thank you, @akmolina28 This resolved it.

**Comment by devotio** [comment]
the mode 'heat_cool' is not automatically translated to "Auto", which also causes the icon not to be created. But is simple to fix this in the card setup.

**Comment by teocannata** [comment]
No news on this?

**Comment by teocannata** [comment]
I found out how to use beta versions on HACS, so I upgraded and tried also the suggested addition of `?v=0.26.0` but I don't see the buttons for the modes.
Should I change something on card's configuration?

Thank you!

**Comment by jacekpaszkowski** [comment]
I have same problem as @teocannata, any ideas?

Thank You.

**Comment by bennealon** [comment]
Hi, i too had this same issue, and the updated build fixes it. However, as a new user of this card, i found the docs a little hard to work out what the modes does - especially since the latest release was broken. Maybe worth a little explanation as to what attribute the modes relates to, and what defining the modes allows you to achieve. I have since worked this out with your fix, but it might help other less-technical folk 👍

**Comment by jacekpaszkowski** [comment]
So maybe there is a problem in HA climate component?

Please see my setup:
card:
![image](https://user-images.githubusercontent.com/4264991/64322879-ad9f9580-cfc3-11e9-8da1-ed740617a013.png)

entity:
![image](https://user-images.githubusercontent.com/4264991/64323005-eb042300-cfc3-11e9-8492-cbbd985d89f2.png)

But as far as i remember before version 0.87 entity there was attribute operation_modes where i had: 
Manufacturer Specific,Heat Eco,Full Power,off.
Now those values are spread in two attributes hvac_modes and preset_modes and Full Power was renamed to boost

Any ideas?

**Comment by G0GUPA** [comment]
> So maybe there is a problem in HA climate component?
> 
> Please see my setup:
> card:
> ![image](https://user-images.githubusercontent.com/4264991/64322879-ad9f9580-cfc3-11e9-8da1-ed740617a013.png)
> 
> entity:
> ![image](https://user-images.githubusercontent.com/4264991/64323005-eb042300-cfc3-11e9-8492-cbbd985d89f2.png)
> 
> But as far as i remember before version 0.87 entity there was attribute operation_modes where i had:
> Manufacturer Specific,Heat Eco,Full Power,off.
> Now those values are spread in two attributes hvac_modes and preset_modes and Full Power was renamed to boost
> 
> Any ideas?

  - type: module
    url: /local/simple-thermostat.js?v=0.26.0-0

**Comment by jacekpaszkowski** [comment]
@G0GUPA I'm using HASC, i've downloaded version 0.26.0-0 and there were no buttons. Now i've tried using "local" and it seems to be better. Now i see two buttons for _hvac_modes_ (heat,off).
![image](https://user-images.githubusercontent.com/4264991/64508615-282b2680-d2de-11e9-8e8c-28316bd9ab9e.png)


Is there an option to get buttons for _preset_modes_?

**Comment by drash1** [comment]
Any information about the _preset_modes_ buttons?

**Comment by nervetattoo** [comment]
See updated docs after 0.26 release.
