### ISSUE TITLE
Add on/off button

### ISSUE THREAD

**Issue by nitobuendia** [nervetattoo/simple-thermostat#65]
It would be a great addition to simply have an on/off button in addition or in exchange for the modes.

Example: 
<img width="1372" alt="Screenshot 2019-07-28 at 09 57 49" src="https://user-images.githubusercontent.com/16522489/62001211-38b48280-b11e-11e9-9ad0-07f39160118e.png">

**Comment by nitobuendia** [comment]
### Sample code
The screenshot on the previous comment was achieved with the following [code on renderHeader()](https://github.com/nitobuendia/simple-thermostat/blob/master/src/index.js#L313):

```js
renderHeader() {
    if (this.name === false) return ''

    let icon = this.icon
    const { state } = this.entity
    if (typeof this.icon === 'object') {
      icon = state in this.icon ? this.icon[state] : false
    }

    return html`
      <header>
        ${(icon &&
          html`
            <ha-icon class="header__icon" .icon=${icon}></ha-icon>
          `) ||
          ''}
        <h2 class="header__title clickable" @click=${() => this.openEntityPopover()}>${this.name}</h2>
        <paper-icon-button style="margin-left: auto;" icon="mdi:power-standby"
            @click=${()=>this.entity.state==='off'?this.setMode('cool'):this.setMode('off')}>
        </paper-icon-button>
      </header>
    `
  }
```

Note: this code requires PR #64 to be implemented, as relies on fixing the "hvac" modes.

### Improvements required

However this code is not production ready. Improvements needed:

1. (Required) On and Cool values are hardcoded. The values needs to:
    1. be inferred from the supported modes,
    1. or, configured from user; who can choose the default mode for "on",
    1. or, replaced setMode() calls for new functions: turnOn() and turnOff().

1. (Optional) Allow for customization:
    1. Allow changing the icon.
    1. Make the colour of the icon change based on "on/off" status.

**Comment by nervetattoo** [comment]
Not going to support this as modes aren't as simple as on/off and I want a uniform UI for controlling modes.
