### ISSUE TITLE
Adding support for Nest thermostats

### ISSUE THREAD

**Issue by syphernl** [nervetattoo/simple-thermostat#66]
Previously I was using the "thermostat-card" but that one is taking up too much space so I'd like to switch to this one instead.

However, I'm running into a few "problems" in getting stuff into the card.

The climate entity provides the following:
```
hvac_modes: heat,off
current_temperature: 24.5
min_temp: 9
max_temp: 32
temperature: 13
hvac_action: idle
preset_mode: null
preset_modes: none,away,eco,Away and Eco
friendly_name: Living Room
supported_features: 17
```

I would like to be able to :
- Switch between heat & off with a button. 
- Turn on Away/Eco with a button

The `mode_type` parameter accepts `operation` or `fan` according to the manual, however the Nest supports neither. 

Is there any way in getting this supported somehow?

**Comment by cooperaj** [comment]
This is probably due to the 0.96 rework of climate components. Most everything was moved to presets which this card doesn't yet support. I'm hoping that's a possibility.

**Comment by darkkatarsis** [comment]
It would be nice if the card was integrated with netatmo also

`hvac_modes: auto,heat
current_temperature: 25.5
min_temp: 7
max_temp: 35
target_temp_step: 0.5
temperature: 23
hvac_action: idle
preset_mode: Schedule
preset_modes: away,boost,Frost Guard,Schedule
battery_level: 99
friendly_name: netatmo_Living room
supported_features: 17`

For now there is no buttons and status is allways Auto

![Screenshot 2019-08-27 at 12 55 29](https://user-images.githubusercontent.com/24244919/63765752-02f3ec80-c8ca-11e9-8dce-5685df766ddd.png)

**Comment by nervetattoo** [comment]
I can only assume this has been fixed in the latest versions so I'm closing the issue. Reopen and provide more details if not.
