### ISSUE TITLE
Temperature change buggy

### ISSUE THREAD

**Issue by craigueh** [nervetattoo/simple-thermostat#70]
I'm using this card with Nest thermostats and the temperature change has always been buggy.
Sometimes it changes, sometimes not, sometimes changes then reverts back. I usually end up just going to the Nest dial in the end to change the temp.

Any idea what could be happening here?

**Comment by ercsey** [comment]
Same problem here. I'm using this card with Tado radiator thermostats with a wall mounted tablet. When I want to change the target temperature have to keep clicking very very fast to change target temperature, but even so after 4 clicking (step size 0.5) it begins to change the target temperature. Sometimes reverts back to the original temperature regardless if I keep clicking or not. Strange. Is it possible to change the waiting time before beginning the service call? Thank you. 
P.S. I'm using version 0.26.0-0

**Comment by justin144** [comment]
Same issue. Would really like this to be fixed. I can’t continue to use this as it is

**Comment by herwinvw** [comment]
Same for me as well. I'm using version 0.28.0.

**Comment by sti0** [comment]
Same here. I'm using mqtt thermostats. Seems that this card updates the temperature to fast (new temperature not actually published to the device or the temperature attribute was not updated). If you set temperature in the more-info dialog it will stay for a few seconds and than the new temperature was published to the entity. Even there is a fall-back to the previous temperature for a second but you could set the desired temperature without the reverts.

**Comment by drash1** [comment]
Hello, I get the sames issue, I recorded a video to illustrate it.
As mentionned the more-info temperature set work perfect as shown at the end of the video.

Would it be possible to implement the mechanisme of temperature change used in the more-info on your card??

![963EFE2E-14C8-4F3D-9AA1-57DD7219A89F](https://user-images.githubusercontent.com/9327424/70356162-0fe28d80-1874-11ea-80b1-60f5352cedbe.GIF)

**Comment by yevon** [comment]
Same here, the problem is how temperature change is handled in code. I take a look at it and I discovered why it happens.

The code applies temperature every one second, it doesn't matter how many times you click the up or down arrows. If it takes 3 seconds to change the target temperature, it will try to update the temperature 3 times. In the meanwhile, lovelace triggers 3 refreshes of current temperature, but on every refresh you are incrementing the current temperature, not the temperature you have set.

For correting this, the debounce function must be deleted, and implement a cancel clicks pattern like described here:

https://stackoverflow.com/questions/17690193/delaying-click-event

**Comment by yevon** [comment]
As a quick workaround for anybody reading this, just increment the time between updates seems to improve quite a lot the situation. I incremented this manually in the code to update the temperature every 5 seconds, so you have time enough to set the target temperature before lovelace triggers a refresh on the widget.

Hotfix:

In www/community/simple-thermostat folder, delete simple-thermostat.js.gz file, and replace simple-thermostat.js contents with the attached file. You can customize the time by replacing the 5000 by any other value, 5000=5s delay before applying new temperature.


[simple-thermostat.zip](https://github.com/nervetattoo/simple-thermostat/files/3937153/simple-thermostat.zip)

**Comment by legomind** [comment]
This bugs me as well.
