### ISSUE TITLE
Controlls with Custom Thermostat

### ISSUE THREAD

**Issue by konecnyna** [nervetattoo/simple-thermostat#75]
I made a really dumb custom thermostat which basically interfaced with my ThiinkEco smart plug.

I set it up by:
```
add_entities([        
        ThinkEcoClimate(
            name='Think Eco',
            target_temperature=req['targetTemp'],
            unit_of_measurement=TEMP_FAHRENHEIT,
            preset=None,
            current_temperature=req['currentTemp'],
            target_humidity=None,
            current_humidity=req['humidity'],
            hvac_mode=hvac_mode,
            hvac_action=None,
            hvac_modes=[HVAC_MODE_COOL, HVAC_MODE_OFF])
    ])
```

I have only two modes `HVAC_MODE_COOL, HVAC_MODE_OFF` but for the live of me can't get them to show.

In the frontend config section Ive added:
```
control:
  - hvac
```

nuttin. Also tried
```
control:
  hvac:
    "off": true // tried "Off" and "OFF" same thing.
```

Any ideas what i need to add to my custom thermostat to have the modes play better with simple-thermostat card?

**Comment by ThirteenTX** [comment]
I have the same issue
Tried numerous combinations and nothing seems to work. This is what it shows under states:

hvac_modes: cool,off 
current_temperature: 75.2 
min_temp: 65 
max_temp: 85 
temperature: 78.5 
hvac_action: idle 
preset_mode: away 
preset_modes: none,away 
friendly_name: Back Room 
supported_features: 17

**Comment by ThirteenTX** [comment]
Weirdly I remove all control settings all together and now it is showing both presets and operation.

**Comment by konecnyna** [comment]
Can you post your card config @ThirteenTX ? Mine is pretty basic as well

```
entity: climate.think_eco
sensors:
  - entity: sensor.apt_humidity
    name: Humidity
step_size: 1
type: 'custom:simple-thermostat'
```

**Comment by ThirteenTX** [comment]
Yeah give me 30 to get back to my pc. 

Regards,
James 
 
  On Wed, Oct 16, 2019 at 6:08 PM, defkon<notifications@github.com> wrote:   
Can you post your card config @ThirteenTX ? Mine is pretty basic as well
entity: climate.think_eco
sensors:
  - entity: sensor.apt_humidity
    name: Humidity
step_size: 1
type: 'custom:simple-thermostat'

**Comment by ThirteenTX** [comment]
Sorry, got tied up. I'll reply in the morning. 

Regards,
James 
 
  On Wed, Oct 16, 2019 at 6:08 PM, defkon<notifications@github.com> wrote:   
Can you post your card config @ThirteenTX ? Mine is pretty basic as well
entity: climate.think_eco
sensors:
  - entity: sensor.apt_humidity
    name: Humidity
step_size: 1
type: 'custom:simple-thermostat'

**Comment by ThirteenTX** [comment]
This is what I have.


<pre><code>type: 'custom:simple-thermostat'
entity: climate.back_room
icon: 'mdi:air-conditioner
sensors:
  - entity: sensor.back_room_humidity
step_size: 0.5
</code></pre>

**Comment by ThirteenTX** [comment]
> 
> 
> Can you post your card config @ThirteenTX ? Mine is pretty basic as well
> 
> ```
> entity: climate.think_eco
> sensors:
>   - entity: sensor.apt_humidity
>     name: Humidity
> step_size: 1
> type: 'custom:simple-thermostat'
> ```

You may want to try crtl+F5 I noticed when I got back to work it still wasn't showing and clearing the cache got it working. Hope it does for you. 
```
entity: climate.back_room
icon: 'mdi:air-conditioner'
sensors:
  - entity: sensor.back_room_humidity
step_size: 0.5
type: 'custom:simple-thermostat'
control:
  - hvac
```
This config now shows just cool and off which is nice! I think it was just a cache issue I was looking over. I tried reinstalling but that wasn't it.

**Comment by nervetattoo** [comment]
Most likely a browser cache issue yes. Always try to hard refresh (ctrl/cmd+r/f5) first or clear browser cache. Closing this.
