### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Kourgiantakis** [nervetattoo/simple-thermostat#77]
Hey Guys,

i've installed simple-thermostat through hacs but i can't get it to work.

After that i opened the Raw-Editor of Lovelace and added:

`resources:
  - url: /local/simple-thermostat.js?v=1
    type: module`

This is what the Readme on Github says.

I then restarted. Then i tried to add another card but there was no "Simple Thermostat" card or anything.

I also tried adding:

` - url: /community_plugin/simple-thermostat/simple-thermostat.js 
 type: module`

This is what the documentation of the hacs plugin says.

With the same effect. It doesn't show up.

For me as a beginner, this is a general problem with HA. It's not detailed enough.

What am i supposed to do after installing it from hacs? Where do i have to add which code and through which editor?

Does it then even show up as a "card" or do i have to add one manually. If yes, which code do i use?

Sorry, but it is really confusing. I've tried for an hour now and im just where i started.

I would really appreciate if you could add it to the documentation.

Thanks in advance.

**Comment by nervetattoo** [comment]
This is more a question about Home Assistant in general. Please read through the [Lovelace UI guide](https://www.home-assistant.io/lovelace) to learn more about configuring cards, or seek help on [the community forum](https://community.home-assistant.io)
