### ISSUE TITLE
Multi-word Text inside the "Preset" buttons is not being centered

### ISSUE THREAD

**Issue by arigit** [nervetattoo/simple-thermostat#79]
See the image - when the text is long (e.g. "Home Evening") the text inside the button is not centered

![image](https://user-images.githubusercontent.com/652673/68533317-06a5e580-02f5-11ea-9216-051353cab1eb.png)

**Comment by nervetattoo** [comment]
Yuck. In general long names and many items looks bad but yes they should have been centered of course :)
