### ISSUE TITLE
When heating not show icon

### ISSUE THREAD

**Issue by pepeEL** [nervetattoo/simple-thermostat#87]
When thermostat heating not showing icon. When power off and idle icon is show correct.

`entity: climate.sypialnia_ogrzewanie
icon:
  heat: 'mdi:radiator'
  idle: 'mdi:radiator-disabled'
  'off': 'mdi:power'
name: Sypialnia
sensors:
  - entity: sensor.airly_humidity
    name: Wilgotność
step_size: 0.5
type: 'custom:simple-thermostat'`
![heating](https://user-images.githubusercontent.com/16692223/70453163-954e8380-1aa8-11ea-8ebc-06e85a7f1aa4.jpg)

**Comment by pepeEL** [comment]
Anybody can help....?

**Comment by adamgorz** [comment]
I have the same...

**Comment by iptvcld** [comment]
same issue

**Comment by iptvcld** [comment]
this worked for me.. change heat to heating and cool to cooling

icon:
  idle: mdi:close-circle-outline
  heating: mdi:radiator
  cooling: mdi:snowflake

**Comment by adamgorz** [comment]
> this worked for me.. change heat to heating and cool to cooling (matched with hvac state)
> 
> icon:
> idle: mdi:close-circle-outline
> heating: mdi:radiator
> cooling: mdi:snowflake

Thanks!
It works. I've only changed from "heat" to "heating" and it's ok!
