### ISSUE TITLE
Decimal places are not displayed anymore.

### ISSUE THREAD

**Issue by JB1985** [nervetattoo/simple-thermostat#90]
Hi, 

i have updated to 0.33.0 but now the decimal places with 0 are not displayed anymore.

![thermostat](https://user-images.githubusercontent.com/9932751/71765859-b9f81880-2ef9-11ea-9e35-c59ee1fad3d3.png)

Previously was displayed, for example 21.0 ° C and now only 21 °C.

I have try decimals: 1 but no luck.

The Problem is only, when the Temparatur is XX.0 if it is xx.1 then the xx.1 is shown.

**Comment by IronicBadger** [comment]
Can confirm.

**Comment by adamgorz** [comment]
Have the same problem in 0.33
