### ISSUE TITLE
Custom commands?

### ISSUE THREAD

**Issue by IronicBadger** [nervetattoo/simple-thermostat#91]
My Venstar T2000 has a bug leaving away mode which I have an open issue for here to give you more context. https://github.com/home-assistant/home-assistant/issues/30417

I was wondering if it's possible to call a `curl` command (or indeed any custom command/script) by configuring an onClick type method for a button preset?

**Comment by nervetattoo** [comment]
I'm afraid no. That is a bit out of scope for what I want in this card at this time. Helping in fixing the bug you've created and linked to here is probably your best way forward.
