### ISSUE TITLE
[feature request] compact mode & tap_action?

### ISSUE THREAD

**Issue by pejotigrek** [nervetattoo/simple-thermostat#95]
hi! thanks for the great card!
while polishing my config I started to think that there are some views in my dashboard, that a compact simple-thermostat card would fit perfectly.. details below :) if I'm wanting too much - shut me down ;) but I'd be happy to read your opinion on this.

ok, here's the **standard/regular** config that I use with HVAC (1) and presets (2), and also additional sensors with text status, current temp, humidity & overall eco state shown as icons next to target temp.

![regular](https://user-images.githubusercontent.com/10796588/72112817-0bac0300-333f-11ea-9773-635a05e7735c.jpg)

what if we could introduce a **short** or **mini** mode, like below.
the (1) and (2) stays intact; target temp goes higher & slightly to the right side; and additional sensor area breaks into two-column table (not one-column like now, so instead of **sensor**-_new line_-**sensor**-... etc. we've got **sensor**-_tab_-**sensor**-_new line_-...); so we could cut out more-or-less the green part of the card:

![shorter](https://user-images.githubusercontent.com/10796588/72112973-680f2280-333f-11ea-8081-409cb24228b7.jpg)

and then the third - **compact** or **nano** one-liner mode.
with HVAC (1) mode displayed only as an icon before the title, and presets (2) only as line of icons after the title.

![compact](https://user-images.githubusercontent.com/10796588/72113264-39457c00-3340-11ea-87f6-a9cced8511d5.jpg)

I know that we can already add some styles to the card, but unfortunately that didn't do the job, at least in my scenario. I'm trying to make a "one screen for each view" config for mobile - like there's a tab/view with only light switches, next tab/view is "climate" only - thermometers, humidity sensors and thermostat etc. unfortunately with larger number of sensors, page starts to scroll - so I thought that making thermosthat card smaller could be useful (and then maybe via additional `tap_action` configuration options I'd add a popup with regular sized thermostat card).

what do you think about that? too much, or maybe there's a chance for adding some of the feats? :)

**Comment by nervetattoo** [comment]
I like the idea of supporting more compact modes so will explore this further, starting with the related changes mentioned in #99.
An expandable card could be interesting as well, with defaulting to the *nano* layout you mention and allowing to expand to the full UI.

**Comment by pejotigrek** [comment]
sounds great! will look forward to it! :)

**Comment by nervetattoo** [comment]
I think the compact mode that can be achieved in 0.34, as documented and shown in the README, will be as far as I'll take it for now. So I will close this issue and hope that you are happy with the new capability @pejotigrek.

**Comment by pejotigrek** [comment]
looks cool, thanks! :)
