### ISSUE TITLE
Allow to control fan speed

### ISSUE THREAD

**Issue by soloam** [nervetattoo/simple-thermostat#97]
In the climate we are able to control the fan speed! Could this be included in this plug-in? I like the minimal aspect of the plug-in, but I miss the speed control!

Thank you

**Comment by nervetattoo** [comment]
Do you not get fan control with:
```yaml
control:
  fan: true
```
?

**Comment by soloam** [comment]
Without

```
control:
  fan: true
```


![image](https://user-images.githubusercontent.com/11949987/73403658-d2383900-42e7-11ea-91bf-5c6efb25ca39.png)

With

control:
  fan: `true`

![image](https://user-images.githubusercontent.com/11949987/73403720-f85dd900-42e7-11ea-9a8c-3c7fa49934af.png)

**Comment by nervetattoo** [comment]
Did you read through https://github.com/nervetattoo/simple-thermostat#usage-of-the-control-config properly?
Fan icons are not defined in the card so you need to manually configure icons and names for the fan controls, and use the control property to use both hvac and fan per the documentation.
