### ISSUE TITLE
[ feature request ] - configurable step-icons

### ISSUE THREAD

**Issue by TheStigh** [nervetattoo/simple-thermostat#99]
Hi @nervetattoo 

It would be nice to be able to have a configuration for step-icons, vertical (as today) or horizontal. Also perhaps change the size as customization. A lot of people use HA on tablets etc for mounting on walls, and with a 10" screen it can be a bit harder to tap the icons to adjust the temperature.

`step-icons: horizontal`
![image](https://user-images.githubusercontent.com/43895442/73166488-372c3d00-40f6-11ea-9c35-779fb27b89b2.png)

`step-icons: vertical`
![image](https://user-images.githubusercontent.com/43895442/73166622-7c506f00-40f6-11ea-9266-0d372227b44e.png)

**Comment by nervetattoo** [comment]
I think this makes sense. Except, right/left aren't great indicators for increasing/decreasing.
I'm close to wrapping up support for this but using +/- instead. It also solves part of #95 by making the end result quite compact. 

![Screen Shot 2020-01-31 at 20 40 29](https://user-images.githubusercontent.com/45449/73569225-4569b880-446a-11ea-8ee5-d8b8fb435907.png)

**Comment by TheStigh** [comment]
@nervetattoo Good choice, just make sure the set temperature is not clickable, or even better, be able to adjust the space between  + - and the digits.

**Comment by ntompson** [comment]
This is great - makes for a nice compact card. But I'm not so sure about the +/- indicators - in the example screen shot above, it sort of looks like the set point is -21.5°C.

What about up / down chevrons for the row layout? I agree that left / right was not a good choice, but I think up / down would look ok.
